-- ============================================================
-- Israel Explorer seeds — GENERATED FILE, DO NOT EDIT BY HAND.
-- Regenerate with: dart run tool/generate_israel_seed_migration.dart
-- Source of truth: lib/shared/data/israel/
-- ============================================================

do $$
begin
  if (select format_type(atttypid, atttypmod) from pg_attribute
      where attrelid = 'public.achievement_definitions'::regclass
        and attname = 'tags' and not attisdropped) = 'text[]' then
    alter table public.achievement_definitions
      alter column tags drop default,
      alter column tags type jsonb using to_jsonb(tags),
      alter column tags set default '[]'::jsonb;
  end if;
end $$;

-- 363 Israel place definitions (insert-if-missing)
insert into public.achievement_definitions (id, title, description, tier, xp_reward, latitude, longitude, claim_radius, collection_id, tags) values
  ('il-region-golan', 'Golan Heights', 'Basalt plateau of volcanoes, waterfalls and vineyards', 'gold', 35, 33.0, 35.75, 22000.0, 'il-regions', '["israel","il-region:golan","il-facet:views"]'::jsonb),
  ('il-region-upper-galilee', 'Upper Galilee', 'Green mountains, the Hula Valley and the Jordan''s sources', 'gold', 35, 33.03, 35.5, 18000.0, 'il-regions', '["israel","il-region:upper-galilee","il-facet:views"]'::jsonb),
  ('il-region-western-galilee', 'Western Galilee', 'From Acre''s walls to the white cliffs of Rosh HaNikra', 'gold', 35, 32.98, 35.15, 15000.0, 'il-regions', '["israel","il-region:western-galilee","il-facet:views"]'::jsonb),
  ('il-region-kinneret', 'Sea of Galilee', 'Israel''s freshwater lake ringed by beaches and holy sites', 'gold', 35, 32.82, 35.58, 12000.0, 'il-regions', '["israel","il-region:kinneret","il-facet:views"]'::jsonb),
  ('il-region-lower-galilee', 'Lower Galilee', 'Rolling hills around Nazareth and Mount Tabor', 'gold', 35, 32.73, 35.35, 14000.0, 'il-regions', '["israel","il-region:lower-galilee","il-facet:views"]'::jsonb),
  ('il-region-valleys', 'Jezreel & Beit She''an Valleys', 'Fertile valleys under Mount Gilboa, rich in springs', 'gold', 35, 32.55, 35.35, 16000.0, 'il-regions', '["israel","il-region:valleys","il-facet:views"]'::jsonb),
  ('il-region-haifa-carmel', 'Haifa & Carmel', 'A port city on a forested mountain above the bay', 'gold', 35, 32.74, 35.02, 14000.0, 'il-regions', '["israel","il-region:haifa-carmel","il-facet:views"]'::jsonb),
  ('il-region-sharon', 'Sharon', 'Coastal plain of citrus groves, cliffs and beaches', 'gold', 35, 32.28, 34.88, 15000.0, 'il-regions', '["israel","il-region:sharon","il-facet:views"]'::jsonb),
  ('il-region-tel-aviv', 'Tel Aviv & Gush Dan', 'The metropolis that never stops', 'gold', 35, 32.07, 34.8, 12000.0, 'il-regions', '["israel","il-region:tel-aviv","il-facet:views"]'::jsonb),
  ('il-region-shfela', 'Judean Lowlands', 'Ancient tels, caves and vineyards between coast and hills', 'gold', 35, 31.75, 34.85, 18000.0, 'il-regions', '["israel","il-region:shfela","il-facet:views"]'::jsonb),
  ('il-region-judean-hills', 'Judean Hills', 'Terraced hills, springs and forests west of Jerusalem', 'gold', 35, 31.76, 35.08, 10000.0, 'il-regions', '["israel","il-region:judean-hills","il-facet:views"]'::jsonb),
  ('il-region-jerusalem', 'Jerusalem', 'The capital, layered with three thousand years of history', 'gold', 35, 31.78, 35.21, 7000.0, 'il-regions', '["israel","il-region:jerusalem","il-facet:views"]'::jsonb),
  ('il-region-dead-sea', 'Dead Sea & Judean Desert', 'The lowest place on Earth and its desert cliffs', 'gold', 35, 31.35, 35.38, 25000.0, 'il-regions', '["israel","il-region:dead-sea","il-facet:views","il-facet:desert"]'::jsonb),
  ('il-region-northern-negev', 'Northern Negev', 'Where the desert begins, around Be''er Sheva', 'gold', 35, 31.2, 34.8, 28000.0, 'il-regions', '["israel","il-region:northern-negev","il-facet:views","il-facet:desert"]'::jsonb),
  ('il-region-negev-highlands', 'Negev Highlands', 'Craters, canyons and Nabataean ruins', 'gold', 35, 30.7, 34.8, 30000.0, 'il-regions', '["israel","il-region:negev-highlands","il-facet:views","il-facet:desert"]'::jsonb),
  ('il-region-arava', 'Arava', 'The long desert valley down to the Red Sea', 'gold', 35, 30.3, 35.12, 35000.0, 'il-regions', '["israel","il-region:arava","il-facet:views","il-facet:desert"]'::jsonb),
  ('il-region-eilat', 'Eilat & the Red Sea', 'Coral reefs at the southern tip of Israel', 'gold', 35, 29.56, 34.95, 12000.0, 'il-regions', '["israel","il-region:eilat","il-facet:views"]'::jsonb),
  ('il-kiryat-shmona', 'Kiryat Shmona', 'Gateway town to the Hula Valley and the Galilee Panhandle', 'bronze', 10, 33.2073, 35.5721, 2500.0, 'il-cities', '["israel","il-region:upper-galilee","il-facet:cities"]'::jsonb),
  ('il-katzrin', 'Katzrin', 'The capital of the Golan Heights', 'bronze', 10, 32.992, 35.691, 2000.0, 'il-cities', '["israel","il-region:golan","il-facet:cities"]'::jsonb),
  ('il-safed', 'Safed', 'The mountain city of Kabbalah, art and blue doors', 'silver', 20, 32.9646, 35.496, 2500.0, 'il-cities', '["israel","il-region:upper-galilee","il-facet:cities","il-facet:faith","il-facet:culture"]'::jsonb),
  ('il-nahariya', 'Nahariya', 'Seaside town on the Ga''aton stream', 'bronze', 10, 33.0058, 35.095, 2500.0, 'il-cities', '["israel","il-region:western-galilee","il-facet:cities","il-facet:sea"]'::jsonb),
  ('il-maalot-tarshiha', 'Ma''alot-Tarshiha', 'Twin Jewish-Arab town in the Galilee hills', 'bronze', 10, 33.0167, 35.2708, 2500.0, 'il-cities', '["israel","il-region:western-galilee","il-facet:cities"]'::jsonb),
  ('il-acre', 'Acre', 'Crusader port city on the northern bay', 'silver', 20, 32.9281, 35.0818, 2500.0, 'il-cities', '["israel","il-region:western-galilee","il-facet:cities","il-facet:history"]'::jsonb),
  ('il-karmiel', 'Karmiel', 'Galilee city famous for its dance festival', 'bronze', 10, 32.919, 35.295, 2500.0, 'il-cities', '["israel","il-region:western-galilee","il-facet:cities"]'::jsonb),
  ('il-sakhnin', 'Sakhnin', 'Galilee town of olive groves and football passion', 'bronze', 10, 32.865, 35.297, 2500.0, 'il-cities', '["israel","il-region:lower-galilee","il-facet:cities"]'::jsonb),
  ('il-shefa-amr', 'Shefa-''Amr', 'Old town with a Crusader fortress and mixed communities', 'bronze', 10, 32.8056, 35.17, 2500.0, 'il-cities', '["israel","il-region:lower-galilee","il-facet:cities"]'::jsonb),
  ('il-tiberias', 'Tiberias', 'Ancient lakeside city of sages and hot springs', 'silver', 20, 32.794, 35.53, 2500.0, 'il-cities', '["israel","il-region:kinneret","il-facet:cities","il-facet:history","il-facet:faith"]'::jsonb),
  ('il-nazareth', 'Nazareth', 'Childhood town of Jesus and the largest Arab city in Israel', 'silver', 20, 32.6996, 35.3035, 2500.0, 'il-cities', '["israel","il-region:lower-galilee","il-facet:cities","il-facet:faith","il-facet:food"]'::jsonb),
  ('il-nof-hagalil', 'Nof HaGalil', 'Hilltop city overlooking Nazareth', 'bronze', 10, 32.7064, 35.3237, 1800.0, 'il-cities', '["israel","il-region:lower-galilee","il-facet:cities"]'::jsonb),
  ('il-migdal-haemek', 'Migdal HaEmek', 'Town on the slopes above the Jezreel Valley', 'bronze', 10, 32.675, 35.24, 1800.0, 'il-cities', '["israel","il-region:valleys","il-facet:cities"]'::jsonb),
  ('il-afula', 'Afula', 'The capital of the Jezreel Valley', 'bronze', 10, 32.6078, 35.2897, 2500.0, 'il-cities', '["israel","il-region:valleys","il-facet:cities"]'::jsonb),
  ('il-beit-shean', 'Beit She''an', 'One of the oldest cities in the land', 'bronze', 10, 32.4973, 35.4964, 1800.0, 'il-cities', '["israel","il-region:valleys","il-facet:cities"]'::jsonb),
  ('il-umm-al-fahm', 'Umm al-Fahm', 'Hillside city with a renowned art gallery', 'bronze', 10, 32.519, 35.153, 2500.0, 'il-cities', '["israel","il-region:valleys","il-facet:cities"]'::jsonb),
  ('il-yokneam', 'Yokneam', 'Tech town at the foot of the Carmel', 'bronze', 10, 32.659, 35.105, 2500.0, 'il-cities', '["israel","il-region:haifa-carmel","il-facet:cities"]'::jsonb),
  ('il-haifa', 'Haifa', 'Port city climbing the slopes of Mount Carmel', 'silver', 20, 32.794, 34.9896, 4000.0, 'il-cities', '["israel","il-region:haifa-carmel","il-facet:cities","il-facet:views"]'::jsonb),
  ('il-kiryat-ata', 'Kiryat Ata', 'Hill town of the Krayot', 'bronze', 10, 32.809, 35.106, 1800.0, 'il-cities', '["israel","il-region:haifa-carmel","il-facet:cities"]'::jsonb),
  ('il-kiryat-bialik', 'Kiryat Bialik', 'Garden town on Haifa Bay', 'bronze', 10, 32.835, 35.085, 1500.0, 'il-cities', '["israel","il-region:haifa-carmel","il-facet:cities"]'::jsonb),
  ('il-tirat-carmel', 'Tirat Carmel', 'Town between the Carmel and the sea', 'bronze', 10, 32.76, 34.971, 1500.0, 'il-cities', '["israel","il-region:haifa-carmel","il-facet:cities"]'::jsonb),
  ('il-nesher', 'Nesher', 'Carmel ridge town with suspension bridges', 'bronze', 10, 32.766, 35.044, 1500.0, 'il-cities', '["israel","il-region:haifa-carmel","il-facet:cities"]'::jsonb),
  ('il-or-akiva', 'Or Akiva', 'Coastal town beside Caesarea', 'bronze', 10, 32.508, 34.918, 1500.0, 'il-cities', '["israel","il-region:sharon","il-facet:cities"]'::jsonb),
  ('il-hadera', 'Hadera', 'Town of eucalyptus groves founded in the swamps', 'bronze', 10, 32.434, 34.919, 2500.0, 'il-cities', '["israel","il-region:sharon","il-facet:cities"]'::jsonb),
  ('il-kfar-saba', 'Kfar Saba', 'Green city of the southern Sharon', 'bronze', 10, 32.175, 34.907, 2500.0, 'il-cities', '["israel","il-region:sharon","il-facet:cities"]'::jsonb),
  ('il-raanana', 'Ra''anana', 'Leafy city with one of Israel''s largest parks', 'bronze', 10, 32.184, 34.871, 2000.0, 'il-cities', '["israel","il-region:sharon","il-facet:cities"]'::jsonb),
  ('il-hod-hasharon', 'Hod HaSharon', 'Quiet city of former moshavot', 'bronze', 10, 32.15, 34.892, 2000.0, 'il-cities', '["israel","il-region:sharon","il-facet:cities"]'::jsonb),
  ('il-herzliya', 'Herzliya', 'Seaside city of marinas and startups', 'bronze', 10, 32.1624, 34.8447, 2500.0, 'il-cities', '["israel","il-region:sharon","il-facet:cities","il-facet:sea"]'::jsonb),
  ('il-ramat-hasharon', 'Ramat HaSharon', 'Garden city on Tel Aviv''s northern edge', 'bronze', 10, 32.146, 34.84, 1800.0, 'il-cities', '["israel","il-region:tel-aviv","il-facet:cities"]'::jsonb),
  ('il-petah-tikva', 'Petah Tikva', 'The "Mother of the Moshavot", founded 1878', 'bronze', 10, 32.087, 34.887, 2500.0, 'il-cities', '["israel","il-region:tel-aviv","il-facet:cities"]'::jsonb),
  ('il-rosh-haayin', 'Rosh HaAyin', 'City at the springs of the Yarkon', 'bronze', 10, 32.095, 34.957, 2000.0, 'il-cities', '["israel","il-region:tel-aviv","il-facet:cities"]'::jsonb),
  ('il-bnei-brak', 'Bnei Brak', 'The world''s Haredi capital', 'bronze', 10, 32.084, 34.835, 1800.0, 'il-cities', '["israel","il-region:tel-aviv","il-facet:cities","il-facet:faith"]'::jsonb),
  ('il-ramat-gan', 'Ramat Gan', 'Diamond Exchange towers and a national park', 'bronze', 10, 32.07, 34.824, 2000.0, 'il-cities', '["israel","il-region:tel-aviv","il-facet:cities"]'::jsonb),
  ('il-givatayim', 'Givatayim', 'Small hill city with big views of Tel Aviv', 'bronze', 10, 32.071, 34.81, 1200.0, 'il-cities', '["israel","il-region:tel-aviv","il-facet:cities"]'::jsonb),
  ('il-kiryat-ono', 'Kiryat Ono', 'Suburban city east of Tel Aviv', 'bronze', 10, 32.063, 34.855, 1200.0, 'il-cities', '["israel","il-region:tel-aviv","il-facet:cities"]'::jsonb),
  ('il-or-yehuda', 'Or Yehuda', 'Home of the Babylonian Jewry Heritage Center', 'bronze', 10, 32.03, 34.855, 1200.0, 'il-cities', '["israel","il-region:tel-aviv","il-facet:cities"]'::jsonb),
  ('il-yehud', 'Yehud-Monosson', 'Town beside Ben Gurion Airport', 'bronze', 10, 32.033, 34.89, 1200.0, 'il-cities', '["israel","il-region:tel-aviv","il-facet:cities"]'::jsonb),
  ('il-tel-aviv', 'Tel Aviv-Yafo', 'The White City by the sea — Israel''s cultural engine', 'silver', 20, 32.0853, 34.7818, 4000.0, 'il-cities', '["israel","il-region:tel-aviv","il-facet:cities","il-facet:culture","il-facet:food"]'::jsonb),
  ('il-holon', 'Holon', 'Israel''s city of children and design', 'bronze', 10, 32.011, 34.779, 2000.0, 'il-cities', '["israel","il-region:tel-aviv","il-facet:cities"]'::jsonb),
  ('il-bat-yam', 'Bat Yam', 'Seaside city with a long promenade', 'bronze', 10, 32.017, 34.75, 1800.0, 'il-cities', '["israel","il-region:tel-aviv","il-facet:cities","il-facet:sea"]'::jsonb),
  ('il-rishon-lezion', 'Rishon LeZion', 'Founded 1882 — birthplace of the anthem and the flag', 'bronze', 10, 31.964, 34.804, 2500.0, 'il-cities', '["israel","il-region:tel-aviv","il-facet:cities"]'::jsonb),
  ('il-ness-ziona', 'Ness Ziona', 'Hill town of orchards and labs', 'bronze', 10, 31.93, 34.798, 1800.0, 'il-cities', '["israel","il-region:shfela","il-facet:cities"]'::jsonb),
  ('il-rehovot', 'Rehovot', 'City of science and citrus', 'bronze', 10, 31.894, 34.811, 2500.0, 'il-cities', '["israel","il-region:shfela","il-facet:cities"]'::jsonb),
  ('il-yavne', 'Yavne', 'Where the sages rebuilt Judaism after 70 CE', 'bronze', 10, 31.878, 34.739, 2000.0, 'il-cities', '["israel","il-region:shfela","il-facet:cities"]'::jsonb),
  ('il-lod', 'Lod', 'Ancient crossroads city with a famous Roman mosaic', 'bronze', 10, 31.951, 34.888, 2000.0, 'il-cities', '["israel","il-region:shfela","il-facet:cities"]'::jsonb),
  ('il-ramla', 'Ramla', 'The only city founded by the Arabs in the land', 'bronze', 10, 31.929, 34.865, 2000.0, 'il-cities', '["israel","il-region:shfela","il-facet:cities","il-facet:history"]'::jsonb),
  ('il-modiin', 'Modi''in', 'Planned city in the land of the Maccabees', 'bronze', 10, 31.898, 35.01, 2500.0, 'il-cities', '["israel","il-region:shfela","il-facet:cities"]'::jsonb),
  ('il-gedera', 'Gedera', 'Bilu pioneers'' town of 1884', 'bronze', 10, 31.814, 34.778, 1500.0, 'il-cities', '["israel","il-region:shfela","il-facet:cities"]'::jsonb),
  ('il-ashdod', 'Ashdod', 'Israel''s busiest port and long sandy beaches', 'bronze', 10, 31.804, 34.655, 3500.0, 'il-cities', '["israel","il-region:shfela","il-facet:cities","il-facet:sea"]'::jsonb),
  ('il-kiryat-malakhi', 'Kiryat Malakhi', 'Development town of the south', 'bronze', 10, 31.73, 34.746, 1500.0, 'il-cities', '["israel","il-region:shfela","il-facet:cities"]'::jsonb),
  ('il-beit-shemesh', 'Beit Shemesh', 'Biblical town at the foot of the Judean Hills', 'bronze', 10, 31.748, 34.988, 2500.0, 'il-cities', '["israel","il-region:judean-hills","il-facet:cities"]'::jsonb),
  ('il-ashkelon', 'Ashkelon', 'Coastal city of 4,000 years and sandstone cliffs', 'bronze', 10, 31.669, 34.572, 3000.0, 'il-cities', '["israel","il-region:shfela","il-facet:cities","il-facet:sea"]'::jsonb),
  ('il-kiryat-gat', 'Kiryat Gat', 'Chip-making town of the Lachish region', 'bronze', 10, 31.61, 34.764, 2000.0, 'il-cities', '["israel","il-region:shfela","il-facet:cities"]'::jsonb),
  ('il-sderot', 'Sderot', 'Resilient town of rock bands and red anemones', 'bronze', 10, 31.525, 34.596, 1800.0, 'il-cities', '["israel","il-region:northern-negev","il-facet:cities","il-facet:desert"]'::jsonb),
  ('il-netivot', 'Netivot', 'Pilgrimage town of the Baba Sali', 'bronze', 10, 31.423, 34.588, 1800.0, 'il-cities', '["israel","il-region:northern-negev","il-facet:cities","il-facet:faith","il-facet:desert"]'::jsonb),
  ('il-ofakim', 'Ofakim', 'Western Negev town by the Patish stream', 'bronze', 10, 31.314, 34.62, 1800.0, 'il-cities', '["israel","il-region:northern-negev","il-facet:cities","il-facet:desert"]'::jsonb),
  ('il-rahat', 'Rahat', 'The largest Bedouin city in Israel', 'bronze', 10, 31.393, 34.754, 2000.0, 'il-cities', '["israel","il-region:northern-negev","il-facet:cities","il-facet:desert"]'::jsonb),
  ('il-beer-sheva', 'Be''er Sheva', 'Abraham''s wells and the capital of the Negev', 'silver', 20, 31.252, 34.791, 4000.0, 'il-cities', '["israel","il-region:northern-negev","il-facet:cities","il-facet:desert"]'::jsonb),
  ('il-arad', 'Arad', 'Desert town above the Dead Sea', 'bronze', 10, 31.261, 35.214, 2000.0, 'il-cities', '["israel","il-region:northern-negev","il-facet:cities","il-facet:desert"]'::jsonb),
  ('il-dimona', 'Dimona', 'Negev town on the road to the Arava', 'bronze', 10, 31.07, 35.033, 2000.0, 'il-cities', '["israel","il-region:northern-negev","il-facet:cities","il-facet:desert"]'::jsonb),
  ('il-yeruham', 'Yeruham', 'Desert town with a lake and a big-crater backyard', 'bronze', 10, 30.988, 34.929, 1800.0, 'il-cities', '["israel","il-region:negev-highlands","il-facet:cities","il-facet:desert"]'::jsonb),
  ('il-mitzpe-ramon', 'Mitzpe Ramon', 'Clifftop town on the rim of the Ramon Crater', 'silver', 20, 30.61, 34.8, 2000.0, 'il-cities', '["israel","il-region:negev-highlands","il-facet:cities","il-facet:views","il-facet:desert"]'::jsonb),
  ('il-eilat', 'Eilat', 'Israel''s southern tip on the Red Sea', 'silver', 20, 29.5577, 34.9519, 4000.0, 'il-cities', '["israel","il-region:eilat","il-facet:cities","il-facet:sea"]'::jsonb),
  ('il-jerusalem', 'Jerusalem', 'The eternal city — holy to three faiths', 'gold', 35, 31.7683, 35.2137, 5000.0, 'il-cities', '["israel","il-region:jerusalem","il-facet:cities","il-facet:history","il-facet:faith"]'::jsonb),
  ('il-metula', 'Metula', 'Israel''s northernmost town, founded 1896', 'silver', 20, 33.279, 35.578, 1200.0, 'il-villages', '["israel","il-region:upper-galilee","il-facet:culture","il-facet:views"]'::jsonb),
  ('il-majdal-shams', 'Majdal Shams', 'Druze village on the slopes of Mount Hermon', 'silver', 20, 33.269, 35.771, 1200.0, 'il-villages', '["israel","il-region:golan","il-facet:culture","il-facet:food","il-facet:views"]'::jsonb),
  ('il-jish', 'Jish (Gush Halav)', 'Maronite village where Aramaic is still taught', 'silver', 20, 33.023, 35.448, 1200.0, 'il-villages', '["israel","il-region:upper-galilee","il-facet:culture"]'::jsonb),
  ('il-amirim', 'Amirim', 'Vegetarian village with a view of the Kinneret', 'silver', 20, 32.938, 35.451, 1200.0, 'il-villages', '["israel","il-region:upper-galilee","il-facet:culture","il-facet:food","il-facet:nature"]'::jsonb),
  ('il-rosh-pina', 'Rosh Pina', 'Restored 1882 pioneer village of stone lanes', 'silver', 20, 32.969, 35.542, 1200.0, 'il-villages', '["israel","il-region:upper-galilee","il-facet:culture","il-facet:history"]'::jsonb),
  ('il-pekiin', 'Peki''in', 'Druze village with an ancient Jewish presence', 'silver', 20, 32.977, 35.332, 1200.0, 'il-villages', '["israel","il-region:western-galilee","il-facet:culture","il-facet:history"]'::jsonb),
  ('il-degania', 'Degania Alef', 'The first kibbutz, founded 1910', 'silver', 20, 32.708, 35.576, 1200.0, 'il-villages', '["israel","il-region:kinneret","il-facet:culture","il-facet:history"]'::jsonb),
  ('il-kfar-kama', 'Kfar Kama', 'Circassian village with its own language and heritage', 'silver', 20, 32.721, 35.443, 1200.0, 'il-villages', '["israel","il-region:lower-galilee","il-facet:culture"]'::jsonb),
  ('il-kfar-tavor', 'Kfar Tavor', 'Old moshava at the foot of Mount Tabor', 'silver', 20, 32.687, 35.422, 1200.0, 'il-villages', '["israel","il-region:lower-galilee","il-facet:culture"]'::jsonb),
  ('il-nahalal', 'Nahalal', 'The first moshav and its famous round layout', 'silver', 20, 32.69, 35.197, 1200.0, 'il-villages', '["israel","il-region:valleys","il-facet:culture","il-facet:history"]'::jsonb),
  ('il-ein-hod', 'Ein Hod', 'Artists'' village on the Carmel slopes', 'silver', 20, 32.7, 34.983, 1200.0, 'il-villages', '["israel","il-region:haifa-carmel","il-facet:culture"]'::jsonb),
  ('il-daliyat-al-karmel', 'Daliyat al-Karmel', 'Druze town of spice markets on the Carmel', 'silver', 20, 32.693, 35.049, 1200.0, 'il-villages', '["israel","il-region:haifa-carmel","il-facet:culture","il-facet:food"]'::jsonb),
  ('il-zichron-yaakov', 'Zichron Ya''akov', 'Rothschild''s wine town on the southern Carmel', 'silver', 20, 32.571, 34.953, 1200.0, 'il-villages', '["israel","il-region:haifa-carmel","il-facet:culture","il-facet:food","il-facet:history"]'::jsonb),
  ('il-neve-shalom', 'Neve Shalom ~ Wahat al-Salam', 'Village where Jewish and Arab families chose to live together', 'silver', 20, 31.818, 34.979, 1200.0, 'il-villages', '["israel","il-region:shfela","il-facet:culture"]'::jsonb),
  ('il-abu-ghosh', 'Abu Ghosh', 'Hummus capital and crusader church in the Judean Hills', 'silver', 20, 31.807, 35.108, 1200.0, 'il-villages', '["israel","il-region:judean-hills","il-facet:culture","il-facet:food"]'::jsonb),
  ('il-ein-kerem', 'Ein Kerem', 'Village of churches, galleries and terraced slopes', 'silver', 20, 31.768, 35.162, 1200.0, 'il-villages', '["israel","il-region:jerusalem","il-facet:culture","il-facet:faith"]'::jsonb),
  ('il-kibbutz-ein-gedi', 'Kibbutz Ein Gedi', 'Desert kibbutz with a botanical garden above the Dead Sea', 'silver', 20, 31.454, 35.387, 1200.0, 'il-villages', '["israel","il-region:dead-sea","il-facet:culture","il-facet:nature","il-facet:desert"]'::jsonb),
  ('il-yotvata', 'Yotvata', 'Arava kibbutz famous for its chocolate milk', 'silver', 20, 29.896, 35.061, 1200.0, 'il-villages', '["israel","il-region:arava","il-facet:culture","il-facet:food","il-facet:desert"]'::jsonb),
  ('il-mount-hermon', 'Mount Hermon', 'Israel''s highest peak and only ski site', 'platinum', 50, 33.307, 35.774, 2000.0, 'il-heights', '["israel","il-region:golan","il-facet:views","il-facet:adventure","il-facet:nature"]'::jsonb),
  ('il-nimrod-fortress', 'Nimrod Fortress', 'Medieval castle guarding the road to Damascus', 'silver', 20, 33.2525, 35.7144, 700.0, 'il-national-parks', '["israel","il-region:golan","il-facet:history","il-facet:nature","il-facet:views"]'::jsonb),
  ('il-banias-springs', 'Banias Springs', 'Spring and Temple of Pan at the foot of the Hermon', 'silver', 20, 33.2486, 35.6943, 700.0, 'il-national-parks', '["israel","il-region:golan","il-facet:history","il-facet:nature","il-facet:water"]'::jsonb),
  ('il-banias-waterfall', 'Banias Waterfall', 'The most powerful waterfall in Israel', 'gold', 35, 33.2378, 35.6787, 800.0, 'il-water', '["israel","il-region:golan","il-facet:water","il-facet:nature"]'::jsonb),
  ('il-saar-falls', 'Sa''ar Falls', 'Roadside cascade fed by Hermon snowmelt', 'silver', 20, 33.24, 35.7038, 900.0, 'il-water', '["israel","il-region:golan","il-facet:water","il-facet:nature"]'::jsonb),
  ('il-mount-bental', 'Mount Bental', 'Volcano-top lookout and bunkers over the Golan', 'silver', 20, 33.1272, 35.7837, 1000.0, 'il-heights', '["israel","il-region:golan","il-facet:views","il-facet:history"]'::jsonb),
  ('il-mitzpe-gadot', 'Mitzpe Gadot', 'Cliff-edge lookout over the Hula Valley', 'silver', 20, 33.0135, 35.6414, 1000.0, 'il-heights', '["israel","il-region:golan","il-facet:views"]'::jsonb),
  ('il-golan-winery', 'Golan Heights Winery', 'The winery that put Israeli wine on the world map', 'bronze', 10, 32.99, 35.7, 900.0, 'il-food', '["israel","il-region:golan","il-facet:food"]'::jsonb),
  ('il-ancient-katzrin', 'Ancient Katzrin', 'Restored Talmudic-era village and synagogue', 'silver', 20, 32.9882, 35.704, 500.0, 'il-heritage', '["israel","il-region:golan","il-facet:history"]'::jsonb),
  ('il-rujm-el-hiri', 'Gilgal Refaim (Rujm el-Hiri)', 'Mysterious 5,000-year-old stone circles', 'gold', 35, 32.9083, 35.8008, 800.0, 'il-heritage', '["israel","il-region:golan","il-facet:history","il-facet:adventure"]'::jsonb),
  ('il-gamla', 'Gamla', 'Rebel town on a camel''s hump, with griffon vultures and a waterfall', 'gold', 35, 32.9036, 35.7406, 1200.0, 'il-nature', '["israel","il-region:golan","il-facet:nature","il-facet:history","il-facet:wildlife"]'::jsonb),
  ('il-yehudiya', 'Nahal Yehudiya', 'Basalt canyon of pools you swim through', 'gold', 35, 32.9435, 35.709, 1500.0, 'il-water', '["israel","il-region:golan","il-facet:water","il-facet:nature","il-facet:adventure"]'::jsonb),
  ('il-meshushim', 'Hexagon Pool (Meshushim)', 'Pool framed by hexagonal basalt columns', 'silver', 20, 32.9425, 35.661, 900.0, 'il-water', '["israel","il-region:golan","il-facet:water","il-facet:nature"]'::jsonb),
  ('il-hamat-gader', 'Hamat Gader', 'Hot springs, Roman baths and an alligator farm', 'silver', 20, 32.683, 35.664, 800.0, 'il-water', '["israel","il-region:golan","il-facet:water","il-facet:nature","il-facet:history","il-facet:wildlife"]'::jsonb),
  ('il-tanur-waterfall', 'Tanur Waterfall (Nahal Iyun)', '30-meter waterfall shaped like an oven chimney', 'silver', 20, 33.2697, 35.5823, 800.0, 'il-water', '["israel","il-region:upper-galilee","il-facet:water","il-facet:nature"]'::jsonb),
  ('il-tel-dan', 'Tel Dan', 'Lush spring forest and a 4,000-year-old gate', 'gold', 35, 33.2486, 35.6525, 900.0, 'il-nature', '["israel","il-region:upper-galilee","il-facet:nature","il-facet:water","il-facet:history"]'::jsonb),
  ('il-nahal-snir', 'Nahal Snir (Hatzbani)', 'Shaded stream walk along a Jordan source', 'silver', 20, 33.234, 35.623, 1000.0, 'il-water', '["israel","il-region:upper-galilee","il-facet:water","il-facet:nature"]'::jsonb),
  ('il-horshat-tal', 'Horshat Tal', 'Ancient oak grove and icy swimming lake', 'silver', 20, 33.216, 35.628, 700.0, 'il-national-parks', '["israel","il-region:upper-galilee","il-facet:history","il-facet:nature","il-facet:water"]'::jsonb),
  ('il-israel-trail-north', 'Israel Trail — Northern Trailhead', 'Start (or finish) the 1,100 km Israel National Trail at Dan', 'gold', 35, 33.239, 35.652, 800.0, 'il-experiences', '["israel","il-region:upper-galilee","il-facet:adventure","il-facet:nature"]'::jsonb),
  ('il-misgav-am', 'Misgav Am Lookout', 'Border-ridge view over the whole Hula Valley', 'silver', 20, 33.247, 35.548, 1000.0, 'il-heights', '["israel","il-region:upper-galilee","il-facet:views"]'::jsonb),
  ('il-tel-hai', 'Tel Hai', 'Courtyard of Trumpeldor''s last stand, 1920', 'silver', 20, 33.234, 35.578, 500.0, 'il-heritage', '["israel","il-region:upper-galilee","il-facet:history"]'::jsonb),
  ('il-manara-cliff', 'Manara Cliff Cable Car', 'Ride the cable car up the Naftali cliff — then zipline down', 'gold', 35, 33.196, 35.544, 800.0, 'il-experiences', '["israel","il-region:upper-galilee","il-facet:adventure","il-facet:views"]'::jsonb),
  ('il-jordan-kayak', 'Kayak the Jordan River', 'Paddle the upper Jordan through the Hula Valley', 'gold', 35, 33.17, 35.61, 1500.0, 'il-experiences', '["israel","il-region:upper-galilee","il-facet:adventure","il-facet:water"]'::jsonb),
  ('il-agamon-hula', 'Agamon Hula — Crane Migration', 'Watch tens of thousands of cranes at dawn', 'gold', 35, 33.108, 35.585, 2000.0, 'il-experiences', '["israel","il-region:upper-galilee","il-facet:adventure","il-facet:wildlife","il-facet:nature"]'::jsonb),
  ('il-hula-reserve', 'Hula Nature Reserve', 'Israel''s first nature reserve — papyrus, water buffalo and birds', 'silver', 20, 33.073, 35.606, 900.0, 'il-nature', '["israel","il-region:upper-galilee","il-facet:nature","il-facet:wildlife","il-facet:water"]'::jsonb),
  ('il-tel-hazor', 'Tel Hazor', 'Biblical Tel — the largest Canaanite city in the land', 'gold', 35, 33.017, 35.568, 800.0, 'il-unesco', '["israel","il-region:upper-galilee","il-facet:history"]'::jsonb),
  ('il-baram', 'Bar''am Synagogue', 'Best-preserved ancient synagogue facade in Israel', 'silver', 20, 33.043, 35.436, 700.0, 'il-national-parks', '["israel","il-region:upper-galilee","il-facet:history","il-facet:nature"]'::jsonb),
  ('il-dalton-winery', 'Dalton Winery', 'Galilee wine on the Dalton plateau', 'bronze', 10, 33.0297, 35.4786, 800.0, 'il-food', '["israel","il-region:upper-galilee","il-facet:food"]'::jsonb),
  ('il-mount-meron', 'Mount Meron', 'Summit trail on the highest mountain inside the Green Line', 'gold', 35, 32.998, 35.41, 1500.0, 'il-heights', '["israel","il-region:upper-galilee","il-facet:views","il-facet:nature"]'::jsonb),
  ('il-meron-tomb', 'Tomb of Rabbi Shimon bar Yochai', 'Pilgrimage site of the Lag BaOmer bonfires', 'silver', 20, 32.98, 35.441, 500.0, 'il-sacred', '["israel","il-region:upper-galilee","il-facet:faith"]'::jsonb),
  ('il-safed-old-city', 'Safed Old City & Artists'' Quarter', 'Kabbalist synagogues and galleries in winding alleys', 'silver', 20, 32.964, 35.493, 500.0, 'il-heritage', '["israel","il-region:upper-galilee","il-facet:history","il-facet:faith","il-facet:culture"]'::jsonb),
  ('il-nahal-amud', 'Nahal Amud', 'Pillar-guarded stream from Safed toward the Kinneret', 'silver', 20, 32.93, 35.49, 2500.0, 'il-water', '["israel","il-region:upper-galilee","il-facet:water","il-facet:nature","il-facet:adventure"]'::jsonb),
  ('il-rosh-hanikra', 'Rosh HaNikra Grottoes', 'Ride the steepest cable car into sea-carved grottoes', 'gold', 35, 33.093, 35.105, 800.0, 'il-experiences', '["israel","il-region:western-galilee","il-facet:adventure","il-facet:sea","il-facet:views"]'::jsonb),
  ('il-keshet-cave', 'Keshet Cave', 'Natural stone arch on a cliff edge', 'silver', 20, 33.0775, 35.197, 900.0, 'il-nature', '["israel","il-region:western-galilee","il-facet:nature","il-facet:views","il-facet:adventure"]'::jsonb),
  ('il-achziv', 'Achziv', 'Lagoons, tide pools and ruins on the northern coast', 'silver', 20, 33.048, 35.102, 700.0, 'il-national-parks', '["israel","il-region:western-galilee","il-facet:history","il-facet:nature","il-facet:sea"]'::jsonb),
  ('il-montfort', 'Montfort Castle', 'Crusader castle of the Teutonic Knights above Nahal Kziv', 'silver', 20, 33.045, 35.226, 900.0, 'il-heritage', '["israel","il-region:western-galilee","il-facet:history","il-facet:nature"]'::jsonb),
  ('il-goren-park', 'Goren Park Lookout', 'Forest lookout over Montfort and Nahal Kziv', 'silver', 20, 33.05, 35.217, 900.0, 'il-heights', '["israel","il-region:western-galilee","il-facet:views"]'::jsonb),
  ('il-nahariya-beach', 'Galei Galil Beach', 'Nahariya''s favorite beach and breakwater', 'bronze', 10, 33.013, 35.092, 700.0, 'il-coast', '["israel","il-region:western-galilee","il-facet:sea"]'::jsonb),
  ('il-yehiam', 'Yehiam Fortress', 'Crusader and Ottoman fortress on a Galilee hill', 'silver', 20, 32.999, 35.221, 700.0, 'il-national-parks', '["israel","il-region:western-galilee","il-facet:history","il-facet:nature"]'::jsonb),
  ('il-ghetto-fighters', 'Ghetto Fighters'' House', 'The world''s first Holocaust museum, founded 1949', 'silver', 20, 32.962, 35.094, 400.0, 'il-museums', '["israel","il-region:western-galilee","il-facet:culture","il-facet:history"]'::jsonb),
  ('il-bahji', 'Shrine of Bahá''u''lláh (Bahjí)', 'Holiest Bahá''í site and its circular gardens', 'gold', 35, 32.943, 35.092, 800.0, 'il-unesco', '["israel","il-region:western-galilee","il-facet:history","il-facet:faith"]'::jsonb),
  ('il-acre-old-city', 'Old City of Acre', 'Ottoman walls over a Crusader city', 'platinum', 50, 32.921, 35.069, 800.0, 'il-unesco', '["israel","il-region:western-galilee","il-facet:history","il-facet:sea","il-facet:food"]'::jsonb),
  ('il-acre-knights-halls', 'Knights'' Halls of Acre', 'Vaulted halls of the Hospitaller fortress', 'silver', 20, 32.9225, 35.0705, 250.0, 'il-museums', '["israel","il-region:western-galilee","il-facet:culture","il-facet:history"]'::jsonb),
  ('il-templars-tunnel', 'Templars'' Tunnel', 'Walk the secret tunnel from the Templar fortress to the port', 'gold', 35, 32.919, 35.067, 250.0, 'il-experiences', '["israel","il-region:western-galilee","il-facet:adventure","il-facet:history"]'::jsonb),
  ('il-ein-afek', 'Ein Afek', 'Last remnant of the coastal swamps — springs and water birds', 'silver', 20, 32.846, 35.111, 900.0, 'il-nature', '["israel","il-region:western-galilee","il-facet:nature","il-facet:water","il-facet:wildlife"]'::jsonb),
  ('il-korazim', 'Korazim', 'Black-basalt Talmudic town above the lake', 'silver', 20, 32.911, 35.564, 700.0, 'il-national-parks', '["israel","il-region:kinneret","il-facet:history","il-facet:nature"]'::jsonb),
  ('il-majrase', 'Bethsaida Valley (Majrase)', 'Wade through warm lagoons where the Jordan meets the lake', 'silver', 20, 32.893, 35.626, 1200.0, 'il-water', '["israel","il-region:kinneret","il-facet:water","il-facet:nature"]'::jsonb),
  ('il-capernaum', 'Capernaum', 'Fishing village of Jesus'' ministry and its white synagogue', 'silver', 20, 32.881, 35.575, 500.0, 'il-sacred', '["israel","il-region:kinneret","il-facet:faith","il-facet:history"]'::jsonb),
  ('il-mount-beatitudes', 'Mount of Beatitudes', 'Where the Sermon on the Mount is remembered', 'silver', 20, 32.881, 35.556, 500.0, 'il-sacred', '["israel","il-region:kinneret","il-facet:faith","il-facet:views"]'::jsonb),
  ('il-tabgha', 'Tabgha', 'Church of the Multiplication and its loaves-and-fishes mosaic', 'silver', 20, 32.873, 35.549, 500.0, 'il-sacred', '["israel","il-region:kinneret","il-facet:faith"]'::jsonb),
  ('il-ancient-boat', 'The Ancient Galilee Boat', 'A 2,000-year-old fishing boat raised from the lake mud', 'silver', 20, 32.848, 35.523, 400.0, 'il-museums', '["israel","il-region:kinneret","il-facet:culture","il-facet:history"]'::jsonb),
  ('il-kursi', 'Kursi', 'Byzantine monastery of the "Miracle of the Swine"', 'silver', 20, 32.8257, 35.6505, 700.0, 'il-national-parks', '["israel","il-region:kinneret","il-facet:history","il-facet:nature","il-facet:faith"]'::jsonb),
  ('il-magdala', 'Magdala', 'Hometown of Mary Magdalene and a first-century synagogue', 'silver', 20, 32.825, 35.515, 500.0, 'il-heritage', '["israel","il-region:kinneret","il-facet:history","il-facet:faith"]'::jsonb),
  ('il-arbel', 'Mount Arbel', 'Cliff with the best view of the Kinneret — and a via ferrata', 'gold', 35, 32.823, 35.499, 1200.0, 'il-national-parks', '["israel","il-region:kinneret","il-facet:history","il-facet:nature","il-facet:views","il-facet:adventure"]'::jsonb),
  ('il-horns-of-hattin', 'Horns of Hattin', 'Extinct volcano where Saladin crushed the Crusaders, 1187', 'silver', 20, 32.7985, 35.4555, 900.0, 'il-heritage', '["israel","il-region:lower-galilee","il-facet:history","il-facet:views"]'::jsonb),
  ('il-maimonides-tomb', 'Tomb of Maimonides', 'Resting place of the great medieval sage', 'silver', 20, 32.79, 35.534, 500.0, 'il-sacred', '["israel","il-region:kinneret","il-facet:faith"]'::jsonb),
  ('il-hamat-tiberias', 'Hamat Tiberias', 'Hot springs and a zodiac mosaic synagogue', 'silver', 20, 32.77, 35.549, 700.0, 'il-national-parks', '["israel","il-region:kinneret","il-facet:history","il-facet:nature","il-facet:water"]'::jsonb),
  ('il-yardenit', 'Yardenit Baptismal Site', 'Baptisms in the Jordan where it leaves the lake', 'silver', 20, 32.711, 35.571, 500.0, 'il-sacred', '["israel","il-region:kinneret","il-facet:faith","il-facet:water"]'::jsonb),
  ('il-tzemach-beach', 'Tzemach Beach', 'Swim in the Kinneret on its southern shore', 'bronze', 10, 32.706, 35.587, 700.0, 'il-coast', '["israel","il-region:kinneret","il-facet:sea","il-facet:water"]'::jsonb),
  ('il-tzippori', 'Tzippori', 'Roman city of the "Mona Lisa of the Galilee" mosaic', 'gold', 35, 32.753, 35.28, 700.0, 'il-national-parks', '["israel","il-region:lower-galilee","il-facet:history","il-facet:nature"]'::jsonb),
  ('il-basilica-annunciation', 'Basilica of the Annunciation', 'The largest church in the Middle East', 'gold', 35, 32.702, 35.2978, 500.0, 'il-sacred', '["israel","il-region:lower-galilee","il-facet:faith"]'::jsonb),
  ('il-mount-precipice', 'Mount Precipice', 'Lookout over the Jezreel Valley from Nazareth''s edge', 'silver', 20, 32.685, 35.297, 1000.0, 'il-heights', '["israel","il-region:lower-galilee","il-facet:views"]'::jsonb),
  ('il-mount-tabor', 'Mount Tabor', 'Dome-shaped mountain of the Transfiguration', 'gold', 35, 32.687, 35.39, 1200.0, 'il-heights', '["israel","il-region:lower-galilee","il-facet:views","il-facet:faith"]'::jsonb),
  ('il-belvoir', 'Belvoir (Kochav HaYarden)', 'Crusader fortress with a sweeping Jordan Valley view', 'silver', 20, 32.596, 35.522, 700.0, 'il-national-parks', '["israel","il-region:valleys","il-facet:history","il-facet:nature","il-facet:views"]'::jsonb),
  ('il-megiddo', 'Tel Megiddo (Armageddon)', 'Biblical Tel of 26 cities — and its water tunnel', 'platinum', 50, 32.585, 35.184, 800.0, 'il-unesco', '["israel","il-region:valleys","il-facet:history"]'::jsonb),
  ('il-beit-shearim', 'Beit She''arim Necropolis', 'Catacombs of the Sanhedrin era carved in chalk', 'gold', 35, 32.702, 35.127, 800.0, 'il-unesco', '["israel","il-region:valleys","il-facet:history","il-facet:adventure"]'::jsonb),
  ('il-ein-harod', 'Ma''ayan Harod', 'Gideon''s spring at the foot of Mount Gilboa', 'silver', 20, 32.55, 35.357, 800.0, 'il-water', '["israel","il-region:valleys","il-facet:water","il-facet:nature"]'::jsonb),
  ('il-mount-gilboa', 'Mount Gilboa', 'Ridge road of irises and paragliders', 'silver', 20, 32.5, 35.395, 3500.0, 'il-heights', '["israel","il-region:valleys","il-facet:views","il-facet:nature"]'::jsonb),
  ('il-beit-alpha', 'Beit Alpha Synagogue', 'Byzantine synagogue with a vivid zodiac mosaic', 'silver', 20, 32.519, 35.428, 700.0, 'il-national-parks', '["israel","il-region:valleys","il-facet:history","il-facet:nature","il-facet:faith"]'::jsonb),
  ('il-gan-hashlosha', 'Gan HaShlosha (Sachne)', 'Turquoise spring pools at 28°C all year', 'gold', 35, 32.501, 35.446, 700.0, 'il-national-parks', '["israel","il-region:valleys","il-facet:history","il-facet:nature","il-facet:water"]'::jsonb),
  ('il-beit-shean-park', 'Beit She''an National Park', 'Roman Scythopolis — colonnades and a theater', 'gold', 35, 32.504, 35.502, 700.0, 'il-national-parks', '["israel","il-region:valleys","il-facet:history","il-facet:nature"]'::jsonb),
  ('il-stella-maris', 'Stella Maris Monastery', 'Carmelite monastery on the tip of Mount Carmel', 'silver', 20, 32.827, 34.97, 500.0, 'il-sacred', '["israel","il-region:haifa-carmel","il-facet:faith","il-facet:views"]'::jsonb),
  ('il-elijahs-cave', 'Elijah''s Cave', 'Cave of the prophet, revered by Jews, Christians, Muslims and Druze', 'silver', 20, 32.83, 34.9693, 250.0, 'il-sacred', '["israel","il-region:haifa-carmel","il-facet:faith"]'::jsonb),
  ('il-haifa-cable-car', 'Haifa Cable Car', 'Bubble cars from Bat Galim up to Stella Maris', 'silver', 20, 32.83, 34.972, 800.0, 'il-experiences', '["israel","il-region:haifa-carmel","il-facet:adventure","il-facet:views"]'::jsonb),
  ('il-german-colony-haifa', 'German Colony, Haifa', 'Templer avenue running up to the Bahá''í Gardens', 'silver', 20, 32.819, 34.989, 500.0, 'il-heritage', '["israel","il-region:haifa-carmel","il-facet:history","il-facet:food"]'::jsonb),
  ('il-louis-promenade', 'Louis Promenade', 'The Carmel-top promenade above the bay', 'silver', 20, 32.809, 34.988, 1000.0, 'il-heights', '["israel","il-region:haifa-carmel","il-facet:views"]'::jsonb),
  ('il-madatech', 'Madatech Science Museum', 'Hands-on science in the Technion''s first building', 'silver', 20, 32.81, 34.9962, 400.0, 'il-museums', '["israel","il-region:haifa-carmel","il-facet:culture"]'::jsonb),
  ('il-dado-beach', 'Dado Beach', 'Haifa''s long promenade beach under the Carmel', 'bronze', 10, 32.795, 34.956, 700.0, 'il-coast', '["israel","il-region:haifa-carmel","il-facet:sea"]'::jsonb),
  ('il-hecht-museum', 'Hecht Museum', 'Archaeology and a 2,400-year-old ship at the University of Haifa', 'silver', 20, 32.76, 35.02, 400.0, 'il-museums', '["israel","il-region:haifa-carmel","il-facet:culture","il-facet:history"]'::jsonb),
  ('il-hai-bar-carmel', 'Hai-Bar Carmel', 'Breeding center returning deer and raptors to the wild', 'silver', 20, 32.745, 35.01, 1200.0, 'il-nature', '["israel","il-region:haifa-carmel","il-facet:nature","il-facet:wildlife"]'::jsonb),
  ('il-atlit', 'Atlit Detainee Camp', 'Where the British held Jewish immigrants — now a museum', 'silver', 20, 32.708, 34.942, 500.0, 'il-heritage', '["israel","il-region:haifa-carmel","il-facet:history"]'::jsonb),
  ('il-muhraka', 'Muhraka', 'Where Elijah faced the prophets of Baal — view to the Jezreel', 'silver', 20, 32.672, 35.089, 1000.0, 'il-heights', '["israel","il-region:haifa-carmel","il-facet:views","il-facet:faith"]'::jsonb),
  ('il-nahal-mearot', 'Nahal Me''arot Caves', 'Prehistoric caves of the Neanderthals and early humans', 'gold', 35, 32.67, 34.966, 800.0, 'il-unesco', '["israel","il-region:haifa-carmel","il-facet:history","il-facet:nature"]'::jsonb),
  ('il-dor-habonim', 'Dor HaBonim Beach', 'Sandstone coves and a natural sea pool', 'bronze', 10, 32.642, 34.93, 1200.0, 'il-coast', '["israel","il-region:haifa-carmel","il-facet:sea","il-facet:nature"]'::jsonb),
  ('il-dor-beach', 'Dor (Tantura) Beach', 'Lagoon beach with islets you can wade to', 'bronze', 10, 32.61, 34.915, 700.0, 'il-coast', '["israel","il-region:haifa-carmel","il-facet:sea"]'::jsonb),
  ('il-carmel-winery', 'Carmel Winery, Zichron Ya''akov', 'Rothschild''s historic 1892 wine cellars', 'bronze', 10, 32.572, 34.9555, 400.0, 'il-food', '["israel","il-region:haifa-carmel","il-facet:food","il-facet:history"]'::jsonb),
  ('il-ramat-hanadiv', 'Ramat Hanadiv', 'Memorial gardens of the Rothschilds and nature trails', 'silver', 20, 32.555, 34.945, 900.0, 'il-nature', '["israel","il-region:haifa-carmel","il-facet:nature"]'::jsonb),
  ('il-nahal-taninim', 'Nahal Taninim', 'Crocodile River — Roman dams and water-powered mills', 'silver', 20, 32.549, 34.905, 1000.0, 'il-national-parks', '["israel","il-region:haifa-carmel","il-facet:history","il-facet:nature","il-facet:water"]'::jsonb),
  ('il-caesarea', 'Caesarea', 'Herod''s harbor city — hippodrome, theater and palace by the sea', 'platinum', 50, 32.5, 34.892, 700.0, 'il-national-parks', '["israel","il-region:sharon","il-facet:history","il-facet:nature","il-facet:sea"]'::jsonb),
  ('il-caesarea-aqueduct', 'Aqueduct Beach, Caesarea', 'Swim beside a 2,000-year-old Roman aqueduct', 'bronze', 10, 32.515, 34.895, 700.0, 'il-coast', '["israel","il-region:sharon","il-facet:sea","il-facet:history"]'::jsonb),
  ('il-caesarea-dive', 'Caesarea Underwater Park', 'Dive among the sunken ruins of Herod''s harbor', 'gold', 35, 32.4995, 34.889, 400.0, 'il-coast', '["israel","il-region:sharon","il-facet:sea","il-facet:adventure","il-facet:history"]'::jsonb),
  ('il-gaash-beach', 'Ga''ash Beach', 'Wild beach under tall sandstone cliffs', 'bronze', 10, 32.233, 34.821, 700.0, 'il-coast', '["israel","il-region:sharon","il-facet:sea"]'::jsonb),
  ('il-apollonia', 'Apollonia (Tel Arsuf)', 'Crusader fortress on the Herzliya cliffs', 'silver', 20, 32.195, 34.8065, 700.0, 'il-national-parks', '["israel","il-region:sharon","il-facet:history","il-facet:nature","il-facet:sea","il-facet:views"]'::jsonb),
  ('il-tel-afek', 'Yarkon Springs — Tel Afek', 'Ottoman fortress of Antipatris at the Yarkon''s source', 'silver', 20, 32.105, 34.93, 700.0, 'il-national-parks', '["israel","il-region:tel-aviv","il-facet:history","il-facet:nature","il-facet:water"]'::jsonb),
  ('il-migdal-tzedek', 'Migdal Tzedek', 'Hilltop fortress overlooking the coastal plain', 'silver', 20, 32.083, 34.955, 700.0, 'il-national-parks', '["israel","il-region:tel-aviv","il-facet:history","il-facet:nature","il-facet:views"]'::jsonb),
  ('il-anu-museum', 'ANU — Museum of the Jewish People', 'The story of the Jewish people worldwide', 'gold', 35, 32.113, 34.804, 400.0, 'il-museums', '["israel","il-region:tel-aviv","il-facet:culture","il-facet:history"]'::jsonb),
  ('il-palmach-museum', 'Palmach Museum', 'Walk-through story of the Palmach fighters', 'silver', 20, 32.108, 34.798, 400.0, 'il-museums', '["israel","il-region:tel-aviv","il-facet:culture","il-facet:history"]'::jsonb),
  ('il-eretz-israel-museum', 'Eretz Israel Museum', 'Glass, coins and folklore around Tel Qasile', 'silver', 20, 32.103, 34.796, 400.0, 'il-museums', '["israel","il-region:tel-aviv","il-facet:culture"]'::jsonb),
  ('il-yarkon-park', 'Yarkon Park', 'Tel Aviv''s great green lung along the river', 'silver', 20, 32.099, 34.81, 1500.0, 'il-nature', '["israel","il-region:tel-aviv","il-facet:nature","il-facet:cities"]'::jsonb),
  ('il-tlv-port', 'Tel Aviv Port (Namal)', 'Wooden boardwalk, farmers'' market and sunset bars', 'bronze', 10, 32.097, 34.774, 400.0, 'il-food', '["israel","il-region:tel-aviv","il-facet:food","il-facet:sea"]'::jsonb),
  ('il-metzitzim-beach', 'Metzitzim Beach', 'Tel Aviv''s north-end family beach', 'bronze', 10, 32.1, 34.772, 700.0, 'il-coast', '["israel","il-region:tel-aviv","il-facet:sea"]'::jsonb),
  ('il-hilton-beach', 'Hilton Beach', 'Surfers, dogs and a famous breakwater', 'bronze', 10, 32.089, 34.77, 700.0, 'il-coast', '["israel","il-region:tel-aviv","il-facet:sea"]'::jsonb),
  ('il-gordon-beach', 'Gordon Beach', 'Matkot, sunsets and the heart of the promenade', 'bronze', 10, 32.083, 34.768, 700.0, 'il-coast', '["israel","il-region:tel-aviv","il-facet:sea","il-facet:cities"]'::jsonb),
  ('il-tlv-museum-of-art', 'Tel Aviv Museum of Art', 'Israeli and modern art in a striking folded building', 'gold', 35, 32.0775, 34.7865, 400.0, 'il-museums', '["israel","il-region:tel-aviv","il-facet:culture"]'::jsonb),
  ('il-azrieli-observatory', 'Azrieli Observatory', 'The whole coastline from the top of the round tower', 'silver', 20, 32.0745, 34.792, 300.0, 'il-heights', '["israel","il-region:tel-aviv","il-facet:views","il-facet:cities"]'::jsonb),
  ('il-sarona', 'Sarona Market', 'Indoor food hall in a restored Templer colony', 'bronze', 10, 32.072, 34.786, 400.0, 'il-food', '["israel","il-region:tel-aviv","il-facet:food"]'::jsonb),
  ('il-carmel-market', 'Carmel Market (Shuk HaCarmel)', 'Tel Aviv''s loudest, tastiest market', 'silver', 20, 32.068, 34.769, 400.0, 'il-food', '["israel","il-region:tel-aviv","il-facet:food"]'::jsonb),
  ('il-white-city', 'The White City (Bauhaus Tel Aviv)', 'Thousands of Bauhaus buildings along Rothschild Boulevard', 'gold', 35, 32.064, 34.774, 800.0, 'il-unesco', '["israel","il-region:tel-aviv","il-facet:history","il-facet:cities","il-facet:culture"]'::jsonb),
  ('il-independence-hall', 'Independence Hall', 'Where Ben-Gurion declared the State, 14 May 1948', 'gold', 35, 32.063, 34.771, 250.0, 'il-heritage', '["israel","il-region:tel-aviv","il-facet:history"]'::jsonb),
  ('il-neve-tzedek', 'Neve Tzedek & HaTachana', 'The first neighborhood outside Jaffa and its old station', 'silver', 20, 32.061, 34.765, 500.0, 'il-heritage', '["israel","il-region:tel-aviv","il-facet:history","il-facet:culture"]'::jsonb),
  ('il-levinsky-market', 'Levinsky Market', 'Spices, burekas and dried fruit since the 1930s', 'bronze', 10, 32.059, 34.773, 300.0, 'il-food', '["israel","il-region:tel-aviv","il-facet:food"]'::jsonb),
  ('il-hatikva-market', 'Hatikva Market', 'Neighborhood shuk with legendary grills', 'bronze', 10, 32.0527, 34.7904, 300.0, 'il-food', '["israel","il-region:tel-aviv","il-facet:food"]'::jsonb),
  ('il-jaffa-flea-market', 'Jaffa Flea Market', 'Antiques by day, restaurants by night', 'bronze', 10, 32.054, 34.757, 300.0, 'il-food', '["israel","il-region:tel-aviv","il-facet:food","il-facet:culture"]'::jsonb),
  ('il-old-jaffa', 'Old Jaffa & Port', 'One of the oldest ports in the world', 'gold', 35, 32.054, 34.752, 500.0, 'il-heritage', '["israel","il-region:tel-aviv","il-facet:history","il-facet:sea","il-facet:views"]'::jsonb),
  ('il-abu-hassan', 'Hummus Abu Hassan', 'Line up for Jaffa''s most famous hummus', 'bronze', 10, 32.051, 34.754, 150.0, 'il-food', '["israel","il-region:tel-aviv","il-facet:food"]'::jsonb),
  ('il-safari-ramat-gan', 'Ramat Gan Safari', 'Drive among zebras and rhinos in the city', 'silver', 20, 32.045, 34.823, 800.0, 'il-nature', '["israel","il-region:tel-aviv","il-facet:nature","il-facet:wildlife"]'::jsonb),
  ('il-design-museum-holon', 'Design Museum Holon', 'Ron Arad''s ribbons of rust-red steel', 'silver', 20, 32.013, 34.779, 400.0, 'il-museums', '["israel","il-region:tel-aviv","il-facet:culture"]'::jsonb),
  ('il-palmachim-beach', 'Palmachim Beach', 'Protected wild beach with sea turtles and ruins', 'bronze', 10, 31.93, 34.697, 700.0, 'il-coast', '["israel","il-region:shfela","il-facet:sea","il-facet:nature","il-facet:wildlife"]'::jsonb),
  ('il-ramla-market', 'Ramla Market', 'Vibrant multicultural shuk at its best on Wednesdays', 'bronze', 10, 31.9269, 34.8743, 300.0, 'il-food', '["israel","il-region:shfela","il-facet:food"]'::jsonb),
  ('il-white-tower-ramla', 'White Tower, Ramla', 'Minaret of the 8th-century White Mosque', 'silver', 20, 31.9273, 34.8659, 250.0, 'il-heritage', '["israel","il-region:shfela","il-facet:history"]'::jsonb),
  ('il-weizmann', 'Weizmann Institute & House', 'World-class science campus and the first president''s home', 'silver', 20, 31.907, 34.809, 500.0, 'il-heritage', '["israel","il-region:shfela","il-facet:history","il-facet:culture"]'::jsonb),
  ('il-tel-gezer', 'Tel Gezer', 'Solomonic gate and a standing-stone high place', 'silver', 20, 31.859, 34.919, 700.0, 'il-national-parks', '["israel","il-region:shfela","il-facet:history","il-facet:nature"]'::jsonb),
  ('il-mini-israel', 'Mini Israel', 'The whole country in miniature — 350 models', 'silver', 20, 31.844, 34.969, 800.0, 'il-experiences', '["israel","il-region:shfela","il-facet:adventure","il-facet:culture"]'::jsonb),
  ('il-latrun-tanks', 'Yad LaShiryon (Latrun)', 'Armored Corps memorial with 200 tanks', 'silver', 20, 31.838, 34.98, 400.0, 'il-museums', '["israel","il-region:shfela","il-facet:culture","il-facet:history"]'::jsonb),
  ('il-latrun-monastery', 'Latrun Monastery Winery', 'Trappist monks'' wine and olive oil', 'bronze', 10, 31.837, 34.984, 300.0, 'il-food', '["israel","il-region:shfela","il-facet:food","il-facet:faith"]'::jsonb),
  ('il-nitzanim', 'Nitzanim Dunes', 'Largest coastal dune reserve in Israel', 'silver', 20, 31.73, 34.611, 1500.0, 'il-nature', '["israel","il-region:shfela","il-facet:nature","il-facet:sea"]'::jsonb),
  ('il-ashkelon-park', 'Ashkelon National Park', 'Canaanite gate and Roman ruins by the sea', 'silver', 20, 31.6577, 34.5444, 900.0, 'il-national-parks', '["israel","il-region:shfela","il-facet:history","il-facet:nature","il-facet:sea"]'::jsonb),
  ('il-beit-guvrin', 'Beit Guvrin-Maresha Caves', 'Bell caves and a land of a thousand caverns', 'platinum', 50, 31.597, 34.897, 800.0, 'il-unesco', '["israel","il-region:shfela","il-facet:history","il-facet:adventure","il-facet:nature"]'::jsonb),
  ('il-tel-lachish', 'Tel Lachish', 'Judean royal city besieged by Sennacherib', 'silver', 20, 31.565, 34.848, 700.0, 'il-national-parks', '["israel","il-region:shfela","il-facet:history","il-facet:nature"]'::jsonb),
  ('il-ein-hemed', 'Ein Hemed (Aqua Bella)', 'Crusader farmhouse and pools in a shaded valley', 'silver', 20, 31.798, 35.128, 700.0, 'il-national-parks', '["israel","il-region:judean-hills","il-facet:history","il-facet:nature","il-facet:water"]'::jsonb),
  ('il-kastel', 'Castel', 'Hilltop battle site of 1948 on the road to Jerusalem', 'silver', 20, 31.796, 35.146, 700.0, 'il-national-parks', '["israel","il-region:judean-hills","il-facet:history","il-facet:nature","il-facet:views"]'::jsonb),
  ('il-sataf', 'Sataf', 'Ancient terraces irrigated by the Sataf and Bikura springs', 'silver', 20, 31.772, 35.124, 800.0, 'il-water', '["israel","il-region:judean-hills","il-facet:water","il-facet:nature"]'::jsonb),
  ('il-yad-kennedy', 'Yad Kennedy', 'Tree-stump memorial with a view over the Judean Hills', 'silver', 20, 31.7493, 35.1348, 800.0, 'il-heights', '["israel","il-region:judean-hills","il-facet:views"]'::jsonb),
  ('il-sorek-cave', 'Soreq Stalactite Cave', 'A cave of dripping stalactites discovered by a quarry blast', 'gold', 35, 31.757, 35.023, 900.0, 'il-nature', '["israel","il-region:judean-hills","il-facet:nature","il-facet:adventure"]'::jsonb),
  ('il-yad-vashem', 'Yad Vashem', 'The World Holocaust Remembrance Center', 'gold', 35, 31.774, 35.175, 400.0, 'il-museums', '["israel","il-region:jerusalem","il-facet:culture","il-facet:history"]'::jsonb),
  ('il-mount-herzl', 'Mount Herzl', 'National cemetery and the grave of Theodor Herzl', 'silver', 20, 31.774, 35.181, 400.0, 'il-heritage', '["israel","il-region:jerusalem","il-facet:history"]'::jsonb),
  ('il-biblical-zoo', 'Jerusalem Biblical Zoo', 'Animals of the Bible around a lake', 'silver', 20, 31.748, 35.178, 600.0, 'il-nature', '["israel","il-region:jerusalem","il-facet:nature","il-facet:wildlife"]'::jsonb),
  ('il-ein-hanya', 'Ein Hanya', 'Restored spring and pools in the Refaim Valley park', 'silver', 20, 31.746, 35.16, 800.0, 'il-water', '["israel","il-region:jerusalem","il-facet:water","il-facet:nature"]'::jsonb),
  ('il-israel-museum', 'Israel Museum', 'Dead Sea Scrolls in the Shrine of the Book', 'platinum', 50, 31.772, 35.204, 400.0, 'il-museums', '["israel","il-region:jerusalem","il-facet:culture","il-facet:history"]'::jsonb),
  ('il-knesset', 'The Knesset', 'Israel''s parliament and the Chagall Hall', 'silver', 20, 31.7767, 35.2054, 400.0, 'il-heritage', '["israel","il-region:jerusalem","il-facet:history"]'::jsonb),
  ('il-mahane-yehuda', 'Mahane Yehuda Market', 'Jerusalem''s shuk — produce by day, bars by night', 'silver', 20, 31.785, 35.212, 400.0, 'il-food', '["israel","il-region:jerusalem","il-facet:food"]'::jsonb),
  ('il-first-station', 'The First Station', 'Old Ottoman railway station turned food and culture hub', 'bronze', 10, 31.7666, 35.2235, 300.0, 'il-food', '["israel","il-region:jerusalem","il-facet:food","il-facet:culture"]'::jsonb),
  ('il-tower-of-david', 'Tower of David', 'Citadel museum of Jerusalem''s history and its night show', 'gold', 35, 31.7761, 35.2283, 250.0, 'il-museums', '["israel","il-region:jerusalem","il-facet:culture","il-facet:history"]'::jsonb),
  ('il-ramparts-walk', 'Ramparts Walk', 'Walk on top of the Old City walls', 'gold', 35, 31.777, 35.2275, 300.0, 'il-experiences', '["israel","il-region:jerusalem","il-facet:adventure","il-facet:views","il-facet:history"]'::jsonb),
  ('il-jerusalem-old-city', 'Old City of Jerusalem', 'Four quarters within Suleiman''s walls', 'platinum', 50, 31.7767, 35.231, 700.0, 'il-unesco', '["israel","il-region:jerusalem","il-facet:history","il-facet:faith"]'::jsonb),
  ('il-zedekiahs-cave', 'Zedekiah''s Cave', 'Vast quarry cavern beneath the Muslim Quarter', 'silver', 20, 31.782, 35.231, 250.0, 'il-nature', '["israel","il-region:jerusalem","il-facet:nature","il-facet:history"]'::jsonb),
  ('il-western-wall-tunnels', 'Western Wall Tunnels', 'Walk along the hidden length of the Western Wall', 'gold', 35, 31.7778, 35.2342, 250.0, 'il-experiences', '["israel","il-region:jerusalem","il-facet:adventure","il-facet:faith","il-facet:history"]'::jsonb),
  ('il-mount-zion', 'Mount Zion', 'King David''s Tomb, the Last Supper room and the Dormition', 'silver', 20, 31.7716, 35.2292, 300.0, 'il-sacred', '["israel","il-region:jerusalem","il-facet:faith"]'::jsonb),
  ('il-city-of-david', 'City of David', 'The original Jerusalem of the Bronze and Iron Ages', 'gold', 35, 31.7735, 35.2355, 500.0, 'il-heritage', '["israel","il-region:jerusalem","il-facet:history"]'::jsonb),
  ('il-hezekiahs-tunnel', 'Hezekiah''s Tunnel', 'Wade knee-deep through a 2,700-year-old water tunnel', 'gold', 35, 31.7716, 35.2357, 250.0, 'il-experiences', '["israel","il-region:jerusalem","il-facet:adventure","il-facet:water","il-facet:history"]'::jsonb),
  ('il-mount-of-olives', 'Mount of Olives', 'The classic panorama of the Old City and the Temple Mount', 'gold', 35, 31.778, 35.244, 1000.0, 'il-heights', '["israel","il-region:jerusalem","il-facet:views","il-facet:faith"]'::jsonb),
  ('il-haas-promenade', 'Haas Promenade (Tayelet)', 'Sunset over Jerusalem from Armon HaNatziv', 'silver', 20, 31.755, 35.225, 1000.0, 'il-heights', '["israel","il-region:jerusalem","il-facet:views"]'::jsonb),
  ('il-qumran', 'Qumran', 'Where the Dead Sea Scrolls were hidden in clifftop caves', 'gold', 35, 31.741, 35.459, 700.0, 'il-national-parks', '["israel","il-region:dead-sea","il-facet:history","il-facet:nature","il-facet:desert"]'::jsonb),
  ('il-einot-tzukim', 'Einot Tzukim (Ein Feshkha)', 'Freshwater pools at the edge of the Dead Sea', 'silver', 20, 31.713, 35.453, 800.0, 'il-water', '["israel","il-region:dead-sea","il-facet:water","il-facet:nature","il-facet:wildlife","il-facet:desert"]'::jsonb),
  ('il-nahal-david', 'Nahal David & David''s Waterfall', 'Desert oasis of ibex and waterfalls in Ein Gedi', 'gold', 35, 31.4675, 35.385, 800.0, 'il-water', '["israel","il-region:dead-sea","il-facet:water","il-facet:nature","il-facet:wildlife","il-facet:desert"]'::jsonb),
  ('il-nahal-arugot', 'Nahal Arugot', 'Ein Gedi''s wilder canyon to the Hidden Waterfall', 'silver', 20, 31.4555, 35.381, 800.0, 'il-water', '["israel","il-region:dead-sea","il-facet:water","il-facet:nature","il-facet:adventure","il-facet:desert"]'::jsonb),
  ('il-masada', 'Masada', 'Herod''s palace-fortress and the last stand of the rebels', 'platinum', 50, 31.3157, 35.3536, 800.0, 'il-unesco', '["israel","il-region:dead-sea","il-facet:history","il-facet:views","il-facet:desert"]'::jsonb),
  ('il-masada-sunrise', 'Sunrise on Masada (Snake Path)', 'Climb the Snake Path in the dark to watch the sun rise over Moab', 'platinum', 50, 31.3155, 35.362, 800.0, 'il-experiences', '["israel","il-region:dead-sea","il-facet:adventure","il-facet:views","il-facet:nature","il-facet:desert"]'::jsonb),
  ('il-dead-sea-float', 'Float in the Dead Sea', 'Float at the lowest place on Earth at Ein Bokek', 'platinum', 50, 31.2, 35.363, 2000.0, 'il-experiences', '["israel","il-region:dead-sea","il-facet:adventure","il-facet:water","il-facet:sea","il-facet:desert"]'::jsonb),
  ('il-mount-sodom', 'Mount Sodom', 'A mountain of salt and Lot''s Wife', 'silver', 20, 31.085, 35.385, 3000.0, 'il-heights', '["israel","il-region:dead-sea","il-facet:views","il-facet:adventure","il-facet:desert"]'::jsonb),
  ('il-flour-cave', 'Flour Cave', 'Soft white chalk cave in Nahal Perazim', 'silver', 20, 31.087, 35.355, 1500.0, 'il-nature', '["israel","il-region:dead-sea","il-facet:nature","il-facet:adventure","il-facet:desert"]'::jsonb),
  ('il-tel-arad', 'Tel Arad', 'Canaanite city and an Israelite fortress with its own temple', 'silver', 20, 31.28, 35.126, 700.0, 'il-national-parks', '["israel","il-region:northern-negev","il-facet:history","il-facet:nature","il-facet:desert"]'::jsonb),
  ('il-tel-beer-sheva', 'Tel Be''er Sheva', 'Biblical Tel with an elaborate water system', 'gold', 35, 31.245, 34.84, 800.0, 'il-unesco', '["israel","il-region:northern-negev","il-facet:history","il-facet:desert"]'::jsonb),
  ('il-iaf-museum', 'Israeli Air Force Museum', 'Dozens of aircraft on the Hatzerim airbase', 'silver', 20, 31.2386, 34.6953, 800.0, 'il-museums', '["israel","il-region:northern-negev","il-facet:culture","il-facet:history","il-facet:desert"]'::jsonb),
  ('il-haluza', 'Haluza', 'Incense Route city buried in the dunes', 'gold', 35, 31.096, 34.651, 1200.0, 'il-unesco', '["israel","il-region:northern-negev","il-facet:history","il-facet:desert"]'::jsonb),
  ('il-mamshit', 'Mamshit', 'The best-preserved Nabataean town on the Incense Route', 'gold', 35, 31.025, 35.064, 800.0, 'il-unesco', '["israel","il-region:northern-negev","il-facet:history","il-facet:desert"]'::jsonb),
  ('il-makhtesh-katan', 'Small Crater (HaMakhtesh HaKatan)', 'The most perfectly shaped erosion crater', 'gold', 35, 30.958, 35.205, 3000.0, 'il-heights', '["israel","il-region:northern-negev","il-facet:views","il-facet:desert"]'::jsonb),
  ('il-makhtesh-gadol', 'Big Crater (HaMakhtesh HaGadol)', 'Colored sands and a desert amphitheater', 'gold', 35, 30.93, 35.01, 4000.0, 'il-heights', '["israel","il-region:northern-negev","il-facet:views","il-facet:desert"]'::jsonb),
  ('il-shivta', 'Shivta', 'Byzantine desert town with three churches', 'gold', 35, 30.881, 34.631, 1000.0, 'il-unesco', '["israel","il-region:negev-highlands","il-facet:history","il-facet:desert"]'::jsonb),
  ('il-ben-gurion-hut', 'Ben-Gurion''s Desert Home', 'The founding prime minister''s hut in Sde Boker', 'silver', 20, 30.874, 34.792, 400.0, 'il-heritage', '["israel","il-region:negev-highlands","il-facet:history","il-facet:desert"]'::jsonb),
  ('il-ein-avdat', 'Ein Avdat Canyon', 'White canyon with a desert spring and ladders up the cliffs', 'gold', 35, 30.823, 34.765, 1200.0, 'il-water', '["israel","il-region:negev-highlands","il-facet:water","il-facet:nature","il-facet:adventure","il-facet:wildlife","il-facet:desert"]'::jsonb),
  ('il-ein-akev', 'Ein Akev', 'Deep emerald pool hidden in the desert', 'silver', 20, 30.8144, 34.8134, 1500.0, 'il-water', '["israel","il-region:negev-highlands","il-facet:water","il-facet:nature","il-facet:adventure","il-facet:desert"]'::jsonb),
  ('il-avdat', 'Avdat', 'Nabataean acropolis over the Zin Valley', 'platinum', 50, 30.794, 34.773, 1200.0, 'il-unesco', '["israel","il-region:negev-highlands","il-facet:history","il-facet:views","il-facet:desert"]'::jsonb),
  ('il-ramon-stargazing', 'Stargazing in the Ramon Crater', 'The Milky Way over Israel''s darkest skies', 'gold', 35, 30.605, 34.785, 3000.0, 'il-experiences', '["israel","il-region:negev-highlands","il-facet:adventure","il-facet:nature","il-facet:desert"]'::jsonb),
  ('il-makhtesh-ramon', 'Ramon Crater', 'The world''s largest erosion crater — 40 km long', 'platinum', 50, 30.58, 34.85, 8000.0, 'il-heights', '["israel","il-region:negev-highlands","il-facet:views","il-facet:nature","il-facet:desert"]'::jsonb),
  ('il-mount-ramon', 'Mount Ramon', 'The highest point of the Negev', 'gold', 35, 30.506, 34.637, 2000.0, 'il-heights', '["israel","il-region:negev-highlands","il-facet:views","il-facet:adventure","il-facet:desert"]'::jsonb),
  ('il-hai-bar-yotvata', 'Hai-Bar Yotvata', 'Oryx, wild asses and ostriches of the desert', 'silver', 20, 29.8569, 35.0368, 1500.0, 'il-nature', '["israel","il-region:arava","il-facet:nature","il-facet:wildlife","il-facet:desert"]'::jsonb),
  ('il-timna', 'Timna Park', 'Solomon''s Pillars, the Mushroom and the world''s oldest copper mines', 'gold', 35, 29.785, 34.968, 3000.0, 'il-national-parks', '["israel","il-region:arava","il-facet:history","il-facet:nature","il-facet:adventure","il-facet:desert"]'::jsonb),
  ('il-red-canyon', 'Red Canyon', 'Narrow canyon of red sandstone walls', 'silver', 20, 29.6689, 34.8703, 1500.0, 'il-water', '["israel","il-region:eilat","il-facet:water","il-facet:nature","il-facet:desert","il-facet:adventure"]'::jsonb),
  ('il-eilat-birding', 'International Birding Center, Eilat', 'A billion birds a year pass over Eilat', 'silver', 20, 29.555, 34.975, 1000.0, 'il-nature', '["israel","il-region:eilat","il-facet:nature","il-facet:wildlife"]'::jsonb),
  ('il-north-beach-eilat', 'North Beach, Eilat', 'Eilat''s lively hotel beach on the lagoon', 'bronze', 10, 29.553, 34.959, 700.0, 'il-coast', '["israel","il-region:eilat","il-facet:sea"]'::jsonb),
  ('il-mount-tzfachot', 'Mount Tzfachot', 'Four countries in one view above the Gulf', 'silver', 20, 29.513, 34.9102, 1000.0, 'il-heights', '["israel","il-region:eilat","il-facet:views","il-facet:desert"]'::jsonb),
  ('il-dolphin-reef', 'Dolphin Reef', 'Swim with dolphins in an open-sea bay', 'gold', 35, 29.529, 34.936, 800.0, 'il-experiences', '["israel","il-region:eilat","il-facet:adventure","il-facet:wildlife","il-facet:sea"]'::jsonb),
  ('il-coral-beach', 'Coral Beach Reserve', 'Snorkel the northernmost coral reef in the world', 'gold', 35, 29.509, 34.92, 700.0, 'il-coast', '["israel","il-region:eilat","il-facet:sea","il-facet:nature","il-facet:adventure"]'::jsonb),
  ('il-underwater-observatory', 'Underwater Observatory', 'Walk down beneath the reef among the fish', 'silver', 20, 29.505, 34.918, 800.0, 'il-experiences', '["israel","il-region:eilat","il-facet:adventure","il-facet:wildlife"]'::jsonb),
  ('il-princess-beach', 'Princess Beach', 'Quiet reef beach at the border with Egypt', 'bronze', 10, 29.494, 34.905, 700.0, 'il-coast', '["israel","il-region:eilat","il-facet:sea","il-facet:adventure"]'::jsonb),
  ('il-israel-trail-south', 'Israel Trail — Southern Trailhead', 'Finish (or start) the Israel National Trail at the Red Sea', 'gold', 35, 29.492, 34.903, 1000.0, 'il-experiences', '["israel","il-region:eilat","il-facet:adventure","il-facet:nature"]'::jsonb),
  ('il-hatzor-haglilit', 'Hatzor HaGlilit', 'Galilee town at the foot of the Kabbalists'' city', 'bronze', 10, 32.98, 35.545, 1500.0, 'il-cities', '["israel","il-region:upper-galilee","il-facet:cities"]'::jsonb),
  ('il-yesud-hamaala', 'Yesud HaMa''ala', 'Pioneer moshava on the shore of the drained Hula lake', 'bronze', 10, 33.06, 35.606, 1200.0, 'il-cities', '["israel","il-region:upper-galilee","il-facet:cities"]'::jsonb),
  ('il-shlomi', 'Shlomi', 'Border town between the hills and the sea', 'bronze', 10, 33.075, 35.145, 1500.0, 'il-cities', '["israel","il-region:western-galilee","il-facet:cities"]'::jsonb),
  ('il-maghar', 'Maghar', 'Druze, Christian and Muslim town on Mount Hazon', 'bronze', 10, 32.89, 35.407, 1800.0, 'il-cities', '["israel","il-region:lower-galilee","il-facet:cities"]'::jsonb),
  ('il-arraba', 'Arraba', 'Town of the Beit Netofa valley', 'bronze', 10, 32.851, 35.337, 1500.0, 'il-cities', '["israel","il-region:lower-galilee","il-facet:cities"]'::jsonb),
  ('il-tamra', 'Tamra', 'Hill town above the Zevulun valley', 'bronze', 10, 32.853, 35.199, 1500.0, 'il-cities', '["israel","il-region:lower-galilee","il-facet:cities"]'::jsonb),
  ('il-kiryat-yam', 'Kiryat Yam', 'Beach town of the Krayot', 'bronze', 10, 32.849, 35.069, 1300.0, 'il-cities', '["israel","il-region:haifa-carmel","il-facet:cities","il-facet:sea"]'::jsonb),
  ('il-kiryat-motzkin', 'Kiryat Motzkin', 'Garden suburb on Haifa Bay', 'bronze', 10, 32.837, 35.079, 1100.0, 'il-cities', '["israel","il-region:haifa-carmel","il-facet:cities"]'::jsonb),
  ('il-kiryat-tivon', 'Kiryat Tivon', 'Wooded hilltop town above Beit She''arim', 'bronze', 10, 32.721, 35.127, 1500.0, 'il-cities', '["israel","il-region:haifa-carmel","il-facet:cities","il-facet:nature"]'::jsonb),
  ('il-ramat-yishai', 'Ramat Yishai', 'Valley town near Nahalal', 'bronze', 10, 32.705, 35.17, 1200.0, 'il-cities', '["israel","il-region:valleys","il-facet:cities"]'::jsonb),
  ('il-isfiya', 'Isfiya', 'Druze town on the Carmel ridge', 'bronze', 10, 32.719, 35.063, 1500.0, 'il-cities', '["israel","il-region:haifa-carmel","il-facet:cities","il-facet:food"]'::jsonb),
  ('il-binyamina', 'Binyamina', 'Rothschild-era moshava between Carmel and Sharon', 'bronze', 10, 32.52, 34.95, 1500.0, 'il-cities', '["israel","il-region:sharon","il-facet:cities"]'::jsonb),
  ('il-pardes-hanna', 'Pardes Hanna-Karkur', 'Bohemian orchard town with a village feel', 'bronze', 10, 32.471, 34.97, 2500.0, 'il-cities', '["israel","il-region:sharon","il-facet:cities"]'::jsonb),
  ('il-baqa', 'Baqa al-Gharbiyye', 'Market town of the Triangle', 'bronze', 10, 32.42, 35.042, 1500.0, 'il-cities', '["israel","il-region:sharon","il-facet:cities"]'::jsonb),
  ('il-kfar-yona', 'Kfar Yona', 'Growing town east of Netanya', 'bronze', 10, 32.317, 34.934, 1500.0, 'il-cities', '["israel","il-region:sharon","il-facet:cities"]'::jsonb),
  ('il-even-yehuda', 'Even Yehuda', 'Green moshava of the Sharon', 'bronze', 10, 32.27, 34.888, 1300.0, 'il-cities', '["israel","il-region:sharon","il-facet:cities"]'::jsonb),
  ('il-kadima-zoran', 'Kadima-Zoran', 'Twin Sharon communities', 'bronze', 10, 32.278, 34.918, 1300.0, 'il-cities', '["israel","il-region:sharon","il-facet:cities"]'::jsonb),
  ('il-tel-mond', 'Tel Mond', 'Orchard town of the central Sharon', 'bronze', 10, 32.256, 34.918, 1200.0, 'il-cities', '["israel","il-region:sharon","il-facet:cities"]'::jsonb),
  ('il-tayibe', 'Tayibe', 'Largest town of the southern Triangle', 'bronze', 10, 32.266, 35.008, 1800.0, 'il-cities', '["israel","il-region:sharon","il-facet:cities"]'::jsonb),
  ('il-qalansawe', 'Qalansawe', 'Triangle town with a Crusader-era tower', 'bronze', 10, 32.285, 34.981, 1300.0, 'il-cities', '["israel","il-region:sharon","il-facet:cities"]'::jsonb),
  ('il-tira', 'Tira', 'Triangle town on the edge of the Sharon', 'bronze', 10, 32.233, 34.95, 1300.0, 'il-cities', '["israel","il-region:sharon","il-facet:cities"]'::jsonb),
  ('il-kafr-qasim', 'Kafr Qasim', 'Town on the eastern Sharon hills', 'bronze', 10, 32.114, 34.977, 1300.0, 'il-cities', '["israel","il-region:tel-aviv","il-facet:cities"]'::jsonb),
  ('il-elad', 'El''ad', 'Haredi city in the foothills', 'bronze', 10, 32.052, 34.951, 1300.0, 'il-cities', '["israel","il-region:tel-aviv","il-facet:cities"]'::jsonb),
  ('il-shoham', 'Shoham', 'Leafy town near Ben Gurion Airport', 'bronze', 10, 31.999, 34.945, 1300.0, 'il-cities', '["israel","il-region:shfela","il-facet:cities"]'::jsonb),
  ('il-beer-yaakov', 'Be''er Ya''akov', 'Moshava turned fast-growing town', 'bronze', 10, 31.942, 34.836, 1200.0, 'il-cities', '["israel","il-region:shfela","il-facet:cities"]'::jsonb),
  ('il-mazkeret-batya', 'Mazkeret Batya', 'Rothschild moshava of 1883 named for his mother', 'bronze', 10, 31.853, 34.846, 1200.0, 'il-cities', '["israel","il-region:shfela","il-facet:cities","il-facet:history"]'::jsonb),
  ('il-kiryat-ekron', 'Kiryat Ekron', 'Town on the site of biblical Ekron', 'bronze', 10, 31.859, 34.821, 1000.0, 'il-cities', '["israel","il-region:shfela","il-facet:cities"]'::jsonb),
  ('il-gan-yavne', 'Gan Yavne', 'Garden town north of Ashdod', 'bronze', 10, 31.787, 34.706, 1200.0, 'il-cities', '["israel","il-region:shfela","il-facet:cities"]'::jsonb),
  ('il-mevaseret-zion', 'Mevaseret Zion', 'Hill town at the gate to Jerusalem', 'bronze', 10, 31.801, 35.15, 1500.0, 'il-cities', '["israel","il-region:judean-hills","il-facet:cities"]'::jsonb),
  ('il-lehavim', 'Lehavim', 'Desert-edge town north of Be''er Sheva', 'bronze', 10, 31.37, 34.815, 1200.0, 'il-cities', '["israel","il-region:northern-negev","il-facet:cities","il-facet:desert"]'::jsonb),
  ('il-meitar', 'Meitar', 'Town at the meeting of Hebron hills and Negev', 'bronze', 10, 31.325, 34.937, 1200.0, 'il-cities', '["israel","il-region:northern-negev","il-facet:cities","il-facet:desert"]'::jsonb),
  ('il-omer', 'Omer', 'Green suburb of Be''er Sheva', 'bronze', 10, 31.265, 34.85, 1300.0, 'il-cities', '["israel","il-region:northern-negev","il-facet:cities","il-facet:desert"]'::jsonb),
  ('il-hura', 'Hura', 'Bedouin town of the northern Negev', 'bronze', 10, 31.298, 34.937, 1300.0, 'il-cities', '["israel","il-region:northern-negev","il-facet:cities","il-facet:desert"]'::jsonb),
  ('il-kseife', 'Kuseife', 'Bedouin town on the road to Arad', 'bronze', 10, 31.245, 35.088, 1300.0, 'il-cities', '["israel","il-region:northern-negev","il-facet:cities","il-facet:desert"]'::jsonb),
  ('il-masade', 'Mas''ade', 'Druze village at the Golan crossroads', 'silver', 20, 33.233, 35.754, 1200.0, 'il-villages', '["israel","il-region:golan","il-facet:culture","il-facet:food"]'::jsonb),
  ('il-buqata', 'Buq''ata', 'Druze village of orchards near Mount Odem', 'silver', 20, 33.202, 35.779, 1200.0, 'il-villages', '["israel","il-region:golan","il-facet:culture","il-facet:food"]'::jsonb),
  ('il-jisr-az-zarqa', 'Jisr az-Zarqa', 'Fishing village with a guesthouse culture on the coast', 'silver', 20, 32.537, 34.912, 1200.0, 'il-villages', '["israel","il-region:haifa-carmel","il-facet:culture","il-facet:sea"]'::jsonb),
  ('il-neot-semadar', 'Neot Semadar', 'Desert art kibbutz with a striking art center tower', 'silver', 20, 30.048, 35.023, 1200.0, 'il-villages', '["israel","il-region:arava","il-facet:culture","il-facet:desert"]'::jsonb),
  ('il-lotan', 'Kibbutz Lotan', 'Eco-kibbutz of mud-domes and birdwatching', 'silver', 20, 29.987, 35.088, 1200.0, 'il-villages', '["israel","il-region:arava","il-facet:culture","il-facet:nature","il-facet:desert"]'::jsonb),
  ('il-kafr-kanna-church', 'Wedding Church, Kafr Kanna', 'Where water became wine at Cana', 'silver', 20, 32.747, 35.342, 400.0, 'il-sacred', '["israel","il-region:lower-galilee","il-facet:faith"]'::jsonb),
  ('il-kinneret-cemetery', 'Kinneret Cemetery', 'Lakeside resting place of Rachel the poetess and the pioneers', 'silver', 20, 32.7195, 35.5712, 500.0, 'il-heritage', '["israel","il-region:kinneret","il-facet:history"]'::jsonb),
  ('il-gan-garoo', 'Gan Garoo Australian Park', 'Kangaroos and koalas in the Beit She''an valley', 'silver', 20, 32.5075, 35.447, 400.0, 'il-nature', '["israel","il-region:valleys","il-facet:nature","il-facet:wildlife"]'::jsonb),
  ('il-bat-galim', 'Bat Galim Beach', 'Old-Haifa promenade at the foot of the cable car', 'bronze', 10, 32.833, 34.979, 400.0, 'il-coast', '["israel","il-region:haifa-carmel","il-facet:sea"]'::jsonb),
  ('il-clandestine-immigration', 'Clandestine Immigration Museum', 'The ship Af Al Pi Chen and the story of the Ha''apala', 'silver', 20, 32.8301, 34.9714, 300.0, 'il-museums', '["israel","il-region:haifa-carmel","il-facet:culture","il-facet:history"]'::jsonb),
  ('il-sdot-yam', 'Sdot Yam Beach', 'Kibbutz beach of Hannah Senesh by Caesarea', 'bronze', 10, 32.493, 34.89, 700.0, 'il-coast', '["israel","il-region:sharon","il-facet:sea"]'::jsonb),
  ('il-givat-olga', 'Givat Olga Beach', 'Cliff beach at the edge of Hadera', 'bronze', 10, 32.443, 34.892, 700.0, 'il-coast', '["israel","il-region:sharon","il-facet:sea"]'::jsonb),
  ('il-herzliya-marina', 'Herzliya Marina', 'Yachts, cafés and breakwater walks', 'bronze', 10, 32.163, 34.795, 700.0, 'il-coast', '["israel","il-region:sharon","il-facet:sea","il-facet:food"]'::jsonb),
  ('il-rabin-square', 'Rabin Square', 'City square of rallies and memory', 'silver', 20, 32.081, 34.781, 300.0, 'il-heritage', '["israel","il-region:tel-aviv","il-facet:history","il-facet:cities"]'::jsonb),
  ('il-dizengoff-square', 'Dizengoff Square', 'Bauhaus circle and Agam''s Fire and Water fountain', 'silver', 20, 32.0778, 34.7742, 250.0, 'il-heritage', '["israel","il-region:tel-aviv","il-facet:history","il-facet:cities","il-facet:culture"]'::jsonb),
  ('il-habima-square', 'Habima Square', 'National theater, Helena Rubinstein pavilion and a sunken garden', 'silver', 20, 32.0725, 34.779, 250.0, 'il-museums', '["israel","il-region:tel-aviv","il-facet:culture","il-facet:cities"]'::jsonb),
  ('il-chagall-windows', 'Chagall Windows, Hadassah', 'Twelve stained-glass tribes of Israel', 'silver', 20, 31.764, 35.148, 400.0, 'il-museums', '["israel","il-region:jerusalem","il-facet:culture","il-facet:faith"]'::jsonb),
  ('il-jerusalem-botanical', 'Jerusalem Botanical Garden', 'Plants of the world around a pond', 'silver', 20, 31.7701, 35.2, 400.0, 'il-nature', '["israel","il-region:jerusalem","il-facet:nature"]'::jsonb),
  ('il-chords-bridge', 'Chords Bridge', 'Calatrava''s harp of a bridge at the city entrance', 'silver', 20, 31.788, 35.202, 250.0, 'il-heritage', '["israel","il-region:jerusalem","il-facet:history","il-facet:cities"]'::jsonb),
  ('il-islamic-art-museum', 'Museum for Islamic Art', 'Calligraphy, ceramics and a famed clock collection', 'silver', 20, 31.7686, 35.213, 250.0, 'il-museums', '["israel","il-region:jerusalem","il-facet:culture"]'::jsonb),
  ('il-yemin-moshe', 'Yemin Moshe & Montefiore Windmill', 'The first neighborhood outside the Old City walls', 'silver', 20, 31.7717, 35.2253, 250.0, 'il-heritage', '["israel","il-region:jerusalem","il-facet:history","il-facet:views"]'::jsonb),
  ('il-gethsemane', 'Garden of Gethsemane', 'Ancient olive trees and the Church of All Nations', 'silver', 20, 31.7794, 35.2397, 250.0, 'il-sacred', '["israel","il-region:jerusalem","il-facet:faith"]'::jsonb),
  ('il-rockefeller-museum', 'Rockefeller Museum', 'Mandate-era archaeology museum in white stone', 'silver', 20, 31.783, 35.236, 250.0, 'il-museums', '["israel","il-region:jerusalem","il-facet:culture","il-facet:history"]'::jsonb),
  ('il-ammunition-hill', 'Ammunition Hill', 'Trenches and memorial of the 1967 battle', 'silver', 20, 31.8, 35.229, 300.0, 'il-heritage', '["israel","il-region:jerusalem","il-facet:history"]'::jsonb),
  ('il-shaar-hagai', 'Sha''ar HaGai', 'Rusting armored convoys of the road to besieged Jerusalem', 'silver', 20, 31.818, 35.027, 600.0, 'il-heritage', '["israel","il-region:judean-hills","il-facet:history"]'::jsonb),
  ('il-neot-kedumim', 'Neot Kedumim', 'Biblical landscape reserve of plants and terraces', 'silver', 20, 31.94, 34.972, 1200.0, 'il-nature', '["israel","il-region:shfela","il-facet:nature","il-facet:faith"]'::jsonb),
  ('il-ben-shemen-forest', 'Ben Shemen Forest', 'Pine forest trails and bike paths in the center', 'silver', 20, 31.948, 34.945, 2000.0, 'il-nature', '["israel","il-region:shfela","il-facet:nature","il-facet:adventure"]'::jsonb),
  ('il-tel-azeka', 'Tel Azeka', 'Hill over the Elah Valley where David met Goliath', 'silver', 20, 31.7, 34.935, 1000.0, 'il-heritage', '["israel","il-region:shfela","il-facet:history","il-facet:views","il-facet:faith"]'::jsonb),
  ('il-yatir-forest', 'Yatir Forest', 'The largest planted forest in Israel, on the desert edge', 'silver', 20, 31.36, 35.045, 4000.0, 'il-nature', '["israel","il-region:northern-negev","il-facet:nature","il-facet:desert"]'::jsonb),
  ('il-abrahams-well', 'Abraham''s Well', 'Visitors center at the well of the patriarch', 'silver', 20, 31.239, 34.79, 300.0, 'il-heritage', '["israel","il-region:northern-negev","il-facet:history","il-facet:faith","il-facet:desert"]'::jsonb),
  ('il-mitzpe-revivim', 'Mitzpe Revivim', 'One of the three first Negev outposts, 1943', 'silver', 20, 31.042, 34.724, 800.0, 'il-heritage', '["israel","il-region:northern-negev","il-facet:history","il-facet:desert"]'::jsonb),
  ('il-yeruham-lake', 'Yeruham Lake', 'A desert lake park of eucalyptus and birds', 'silver', 20, 30.993, 34.897, 800.0, 'il-water', '["israel","il-region:negev-highlands","il-facet:water","il-facet:nature","il-facet:wildlife","il-facet:desert"]'::jsonb),
  ('il-nitzana', 'Nitzana', 'Byzantine Nessana and a desert education village', 'silver', 20, 30.88, 34.42, 1500.0, 'il-heritage', '["israel","il-region:negev-highlands","il-facet:history","il-facet:desert"]'::jsonb),
  ('il-zikim-beach', 'Zikim Beach', 'Wild southern beach of sandstone ridges and dunes', 'bronze', 10, 31.6125, 34.5043, 700.0, 'il-coast', '["israel","il-region:shfela","il-facet:sea","il-facet:nature"]'::jsonb),
  ('il-galil-mountain-winery', 'Galil Mountain Winery', 'Kibbutz Yiron''s winery among Galilee vineyards', 'bronze', 10, 33.075, 35.452, 1000.0, 'il-food', '["israel","il-region:upper-galilee","il-facet:food","il-facet:views"]'::jsonb),
  ('il-biria-forest', 'Biria Forest', 'Pine forest and ruins on the hills above Safed', 'silver', 20, 32.992, 35.515, 2500.0, 'il-nature', '["israel","il-region:upper-galilee","il-facet:nature"]'::jsonb),
  ('il-shavei-zion-beach', 'Shavei Zion Beach', 'Quiet moshav beach with rocky pools', 'bronze', 10, 32.984, 35.08, 700.0, 'il-coast', '["israel","il-region:western-galilee","il-facet:sea"]'::jsonb),
  ('il-marys-well', 'Mary''s Well & St. Gabriel Church', 'The Orthodox site of the Annunciation over Nazareth''s spring', 'silver', 20, 32.709, 35.302, 300.0, 'il-sacred', '["israel","il-region:lower-galilee","il-facet:faith","il-facet:water"]'::jsonb),
  ('il-wadi-nisnas', 'Wadi Nisnas', 'Haifa''s Arab market quarter of street art and falafel', 'bronze', 10, 32.815, 34.993, 300.0, 'il-food', '["israel","il-region:haifa-carmel","il-facet:food","il-facet:culture"]'::jsonb),
  ('il-nahalat-binyamin', 'Nahalat Binyamin Crafts Fair', 'Artists'' street market beside the Carmel Market', 'bronze', 10, 32.0662, 34.7703, 200.0, 'il-food', '["israel","il-region:tel-aviv","il-facet:food","il-facet:culture"]'::jsonb),
  ('il-ayalon-institute', 'Ayalon Institute', 'A secret bullet factory hidden under a kibbutz laundry', 'silver', 20, 31.9161, 34.8098, 400.0, 'il-heritage', '["israel","il-region:shfela","il-facet:history","il-facet:adventure"]'::jsonb),
  ('il-garden-tomb', 'The Garden Tomb', 'Quiet garden around a rock-cut tomb outside Damascus Gate', 'silver', 20, 31.784, 35.23, 200.0, 'il-sacred', '["israel","il-region:jerusalem","il-facet:faith"]'::jsonb),
  ('il-ben-gurion-grave', 'Ben-Gurion''s Grave Lookout', 'Resting place above the Zin canyon at sunset', 'silver', 20, 30.851, 34.783, 400.0, 'il-heights', '["israel","il-region:negev-highlands","il-facet:views","il-facet:history","il-facet:desert"]'::jsonb)
on conflict (id) do nothing;

-- 14 Israel list completion bonuses
insert into public.collection_definitions (id, name, bonus_xp) values
  ('il-regions', 'Regions of Israel', 300),
  ('il-cities', 'Cities & Towns', 250),
  ('il-villages', 'Villages & Communities', 200),
  ('il-unesco', 'UNESCO World Heritage', 400),
  ('il-national-parks', 'National Parks', 300),
  ('il-nature', 'Nature Reserves & Caves', 250),
  ('il-water', 'Springs, Streams & Waterfalls', 250),
  ('il-coast', 'Beaches & Reefs', 200),
  ('il-heights', 'Peaks, Craters & Viewpoints', 250),
  ('il-heritage', 'History & Heritage', 250),
  ('il-sacred', 'Sacred Places', 250),
  ('il-museums', 'Museums', 200),
  ('il-food', 'Markets, Food & Wine', 200),
  ('il-experiences', 'Iconic Experiences', 400)
on conflict (id) do update set name = excluded.name, bonus_xp = excluded.bonus_xp;

-- 50 Israel activity quests
insert into public.quest_definitions (id, title, xp_reward, max_completions, source) values
  ('il-q-israel-trail-section', 'Hike a Section of the Israel Trail', 60, 20, 'activity'),
  ('il-q-israel-trail-complete', 'Complete the Israel National Trail', 1000, 1, 'activity'),
  ('il-q-yam-le-yam', 'Sea to Sea (Yam LeYam)', 200, 1, 'activity'),
  ('il-q-golan-trail', 'Hike the Golan Trail', 250, 1, 'activity'),
  ('il-q-wet-hike', 'Wet Hike in the Golan', 70, 5, 'activity'),
  ('il-q-full-moon-hike', 'Full-Moon Desert Hike', 90, 5, 'activity'),
  ('il-q-negev-stars', 'Sleep Under the Negev Stars', 60, 5, 'activity'),
  ('il-q-kinneret-camp', 'Camp on the Kinneret Shore', 40, 5, 'activity'),
  ('il-q-bedouin-tent', 'A Night in a Bedouin Tent', 50, 1, 'activity'),
  ('il-q-red-sea-dive', 'Scuba Dive the Red Sea', 80, 10, 'activity'),
  ('il-q-med-surf', 'Surf the Mediterranean', 60, 10, 'activity'),
  ('il-q-sup-tel-aviv', 'Stand-Up Paddle off Tel Aviv', 40, 5, 'activity'),
  ('il-q-kinneret-crossing', 'Swim Across the Kinneret', 150, 1, 'activity'),
  ('il-q-hummus-crawl', 'Hummus Crawl', 60, 5, 'activity'),
  ('il-q-shakshuka', 'Shakshuka for Breakfast', 20, 1, 'activity'),
  ('il-q-sabich', 'Sabich in Ramat Gan', 25, 1, 'activity'),
  ('il-q-druze-pita', 'Druze Pita with Labneh', 30, 1, 'activity'),
  ('il-q-knafeh-nazareth', 'Knafeh in Nazareth', 25, 1, 'activity'),
  ('il-q-friday-shuk', 'Friday at the Shuk', 30, 10, 'activity'),
  ('il-q-golan-wine', 'Wine Tasting in the Golan', 50, 5, 'activity'),
  ('il-q-shabbat-dinner', 'Join a Shabbat Dinner', 40, 10, 'activity'),
  ('il-q-independence-mangal', 'Independence Day Mangal', 30, 5, 'activity'),
  ('il-q-lag-baomer', 'Lag BaOmer Bonfire', 30, 5, 'activity'),
  ('il-q-sukkah', 'Eat in a Sukkah', 20, 1, 'activity'),
  ('il-q-western-wall-note', 'A Note in the Wall', 25, 1, 'activity'),
  ('il-q-order-in-hebrew', 'Order in Hebrew', 20, 1, 'activity'),
  ('il-q-arabic-words', 'Ten Words in Arabic', 25, 1, 'activity'),
  ('il-q-light-festival', 'Jerusalem Festival of Light', 30, 5, 'activity'),
  ('il-q-karmiel-dance', 'Karmiel Dance Festival', 30, 5, 'activity'),
  ('il-q-red-sea-jazz', 'Red Sea Jazz Festival', 30, 5, 'activity'),
  ('il-q-acre-fringe', 'Acre Fringe Theatre Festival', 30, 5, 'activity'),
  ('il-q-white-night', 'Tel Aviv White Night', 30, 5, 'activity'),
  ('il-q-ramon-rappel', 'Rappel into the Ramon Crater', 100, 1, 'activity'),
  ('il-q-arbel-cliff', 'Climb the Arbel Cliff Path', 80, 1, 'activity'),
  ('il-q-desert-jeep', 'Jeep Tour in the Desert', 50, 5, 'activity'),
  ('il-q-camel-ride', 'Ride a Camel in the Negev', 30, 1, 'activity'),
  ('il-q-gilboa-paraglide', 'Paraglide off Mount Gilboa', 90, 1, 'activity'),
  ('il-q-hermon-ski', 'Ski the Hermon', 70, 5, 'activity'),
  ('il-q-dead-sea-mud', 'Dead Sea Mud Bath', 25, 5, 'activity'),
  ('il-q-hot-springs', 'Soak in the Hot Springs', 25, 5, 'activity'),
  ('il-q-spot-ibex', 'Spot a Nubian Ibex', 30, 1, 'activity'),
  ('il-q-griffon-vultures', 'Griffon Vultures at Gamla', 30, 1, 'activity'),
  ('il-q-red-anemones', 'Red South (Darom Adom)', 30, 5, 'activity'),
  ('il-q-milky-way-photo', 'Photograph the Milky Way', 80, 1, 'activity'),
  ('il-q-arbel-sunrise-photo', 'Kinneret Sunrise from Arbel', 50, 1, 'activity'),
  ('il-q-train-north-south', 'Nahariya to Be''er Sheva by Train', 50, 1, 'activity'),
  ('il-q-bike-promenade', 'Bike the Tel Aviv Promenade', 30, 5, 'activity'),
  ('il-q-kibbutz-volunteer', 'Volunteer on a Kibbutz', 80, 1, 'activity'),
  ('il-q-tu-bishvat-tree', 'Plant a Tree on Tu BiShvat', 30, 5, 'activity'),
  ('il-q-beach-cleanup', 'Beach Cleanup', 30, 10, 'activity')
on conflict (id) do update set title = excluded.title, xp_reward = excluded.xp_reward, max_completions = excluded.max_completions, source = excluded.source;

-- 36 Israel master achievements
insert into public.master_achievement_definitions (id, title, xp_reward) values
  ('il-master-regions-5', 'Region Hopper', 100),
  ('il-master-regions-10', 'Across the Land', 200),
  ('il-master-regions-all', 'Every Corner of Israel', 500),
  ('il-master-north-to-south', 'From Metula to Eilat', 200),
  ('il-master-high-low', 'Highest & Lowest', 200),
  ('il-master-four-seas', 'Four Seas', 500),
  ('il-master-israel-trail', 'End to End', 200),
  ('il-master-dawn-dusk', 'Dawn & Dusk', 100),
  ('il-master-big-three', 'The Big Three', 100),
  ('il-master-incense-route', 'The Incense Route', 200),
  ('il-master-biblical-tels', 'Biblical Tels', 200),
  ('il-master-craters', 'Three Craters', 200),
  ('il-master-crusader-castles', 'Crusader Castles', 200),
  ('il-master-roman-israel', 'Roman Israel', 100),
  ('il-master-galilee-footsteps', 'Footsteps in the Galilee', 100),
  ('il-master-three-faiths', 'City of Three Faiths', 100),
  ('il-master-waterfalls', 'Waterfall Chaser', 100),
  ('il-master-golan-ranger', 'Golan Ranger', 100),
  ('il-master-jerusalem-insider', 'Jerusalem Insider', 200),
  ('il-master-tel-aviv-local', 'Tel Aviv Local', 100),
  ('il-master-red-sea', 'Red Sea Diver', 100),
  ('il-master-desert-soul', 'Desert Soul', 100),
  ('il-master-time-traveler', 'Keeper of History', 200),
  ('il-master-pilgrim', 'Pilgrim', 100),
  ('il-master-flavor-hunter', 'Taste of Israel', 100),
  ('il-master-thrill-seeker', 'Adrenaline Junkie', 100),
  ('il-master-water-soul', 'Spring Chaser', 100),
  ('il-master-horizon-hunter', 'Horizon Hunter', 100),
  ('il-master-wild-tracker', 'Wild Tracker', 100),
  ('il-master-city-hopper', 'City Hopper', 200),
  ('il-master-unesco', 'World Heritage Collector', 200),
  ('il-master-park-ranger', 'Park Ranger', 200),
  ('il-master-experiences', 'Bucket List: Israel', 500),
  ('il-master-places-25', 'Israel Explorer', 100),
  ('il-master-places-100', 'Israel Expert', 200),
  ('il-master-places-250', 'Legend of the Land', 500)
on conflict (id) do update set title = excluded.title, xp_reward = excluded.xp_reward;

-- Revisit cooldown — adds the Israel regions, cities and villages
create or replace function public.revisit_cooldown(p_achievement_id text)
returns interval
language sql
stable
set search_path = public
as $$
  select case
    when (select collection_id
          from public.achievement_definitions
          where id = p_achievement_id)
         in ('continents', 'europe', 'americas', 'africa', 'asia', 'south-america', 'oceania', 'capitals', 'il-regions', 'il-cities', 'il-villages')
      then interval '7 days'
    else interval '1 hour'
  end;
$$;

revoke execute on function public.revisit_cooldown(text) from public, anon, authenticated;
